### ISSUE TITLE
Vulkan DynamicLoader returns null for vkGetInstanceProcAddr & vkGetDeviceProcAddr

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2123] opened 2024-01-10 04:42 UTC
Since MoltenVK's static symbols have been hidden (see #2121), the Vulkan DynamicLoader returns null for `vkGetInstanceProcAddr` & `vkGetDeviceProcAddr` functions when linking directly to MoltenVK, i.e. 

`static const vk::DynamicLoader dl( "libMoltenVK.dylib" );`

`vkGetInstanceProcAddr = dl.getProcAddress<PFN_vkGetInstanceProcAddr>( "vkGetInstanceProcAddr" )` yields null.
`vkGetDeviceProcAddr = dl.getProcAddress<PFN_vkGetDeviceProcAddr>( "vkGetDeviceProcAddr" )` yields null.
`VULKAN_HPP_DEFAULT_DISPATCHER.init( vkGetInstanceProcAddr )` no longer works.

This breaks my app which links to MoltenVK when in release mode (vulkan loader is used for debugging mode only).

In addition it breaks SDL when trying to create a Vulcan window (`SDL_CreateWindow`).  The SDL error message is:

_Failed to find vkGetInstanceProcAddr in either executable or libMoltenVK.dylib: (null)_

Even though symbols have been hidden for static linking, shouldn't they remain available to the DynamicLoader?  How  will MoltenVK 1.2.7 behave when delivered as part of the new Vulkan SDK 1.3.275?

(FYI - Removal of static symbols is a pretty disruptive change to be happening so late in a release cycle without notice.  While I can adapt in due time to the removal of static symbols, retaining dynamic PFN address retrieval for MoltenVK is critical. Otherwise you are basically saying the Vulkan loader is mandatory and MoltenVK should no longer be used directly.)

**Comment by billhollings** [comment] 2024-01-10 13:50
Thanks for testing it, and posting this! It will help us get this right.

The default MoltenVK build is now the same hidden-symbols build used in the SDK in previous releases. It's also compatible with how Volk works.

So we need to figure out what is needed for other dynamic loaders like the Vulkan Dynamic Loader and SDL.

@richard-lunarg Can you comment on how the SDK loader interacts with MoltenVK to access `vkGetInstanceProcAddr()` and `vkGetDeviceProcAddr()`. I agree with @SRSaunders that perhaps those two functions should be static. Thoughts?

@SRSaunders In the meantime, building MoltenVK with `MVK_HIDE_VULKAN_SYMBOLS=0` will get you the same static build that was the default in previous releases. What happens when you try that?

**Comment by SRSaunders** [comment] 2024-01-10 14:43
> The default MoltenVK build is now the same hidden-symbols build used in the SDK in previous releases

Something must be different about the new 1.2.7 build.  If I change my build include path and library path from my local build of MoltenVK 1.2.7 (main head) located at `.../MoltenVK/Package/Release/MoltenVK/...` to the previous SDK build at `.../VulkanSDK/1.3.268.1/MoltenVK/...`, everything works fine.  The Vulkan Dynamic Loader and SDL both pick up the necessary symbols at runtime from `libMoltenVK.dylib`.  If I use my local 1.2.7 build the symbols are not found.

> In the meantime, building MoltenVK with MVK_HIDE_VULKAN_SYMBOLS=0 will get you the same static build that was the default in previous releases.

This does work, but is only useful in the dev environment.  For end-users, they need to use MoltenVK as provided by the Vulkan SDK.  I don't want them building local versions of MoltenVK to make things work - too much of a barrier.

**Comment by billhollings** [comment] 2024-01-10 15:54
On further investigation of the Volk in the MoltenVK Cube demo, it uses the default SDK `/usr/local/lib/libvulkan.dylib` if it can't find `libMoltenVK.dylib` locally. So I'll have to update the Cube demo in MoltenVK to copy `libMoltenVK.dylib` from the MoltenVK build, to make the MoltenVK Cube demo a standalone build, that doesn't require the SDK to be installed.

Then, once connected to `libMoltenVK.dylib` directly, Volk also chokes on not finding `vkGetInstanceProcAddr()` within `libMoltenVK.dylib`. I was able to fix Volk by statically exposing just this one function.

@SRSaunders Can you try building MoltenVK _with the default hidden symbols_, but also with the following change in `vulkan.mm`, please:

    MVK_PUBLIC_SYMBOL PFN_vkVoidFunction vkGetInstanceProcAddr(

Note the change of `MVK_PUBLIC_VULKAN_SYMBOL` to `MVK_PUBLIC_SYMBOL`. This statically exposes `vkGetInstanceProcAddr()`.

If that isn't enough, try making the same change to `vkGetDeviceProcAddr()` in `vulkan.mm`.

Either way, let me know what happens, please.

**Comment by billhollings** [comment] 2024-01-10 15:55
>If I change my build include path and library path from my local build of MoltenVK 1.2.7 [snip] to the previous SDK build [snip] everything works fine with no code changes
> ...
> For end-users, they need to use MoltenVK as provided by the Vulkan SDK.

@richard-lunarg My understanding was that, for the past few SDK releases, MoltenVK in the SDK has been built with MoltenVK static symbols hidden (`MVK_HIDE_VULKAN_SYMBOLS=1`). Is that not the case?

**Comment by SRSaunders** [comment] 2024-01-10 16:44
> Can you try building MoltenVK with the default hidden symbols, but also with the following change in vulkan.mm, please:
> 
> `MVK_PUBLIC_SYMBOL PFN_vkVoidFunction vkGetInstanceProcAddr(`

I had to do some juggling to call `(*vkGetInstanceProcAddr)(m_VulkanInstance, "vkGetDeviceProcAddr" )` only **_after_** device creation, otherwise you get null.  However, with code changes in place it works!

You can get away with exposing only `vkGetInstanceProcAddr` if you are careful as I had to be above.  I wonder if other applications may depend on having `vkGetDeviceProcAddr` defined earlier?  I'm not sure, others will have to comment.

**Comment by billhollings** [comment] 2024-01-10 18:46
> I had to do some juggling to call `(*vkGetInstanceProcAddr)( m_VulkanInstance, "vkGetDeviceProcAddr" )` only **_after_** device creation, otherwise you get null. However, with code changes in place it works!

Do you mean after _device_ creation, or _instance_ creation?

**Comment by Steveice10** [comment] 2024-01-10 18:49
One workaround is to use the symbol name “vk_icdGetInstanceProcAddr” as that is an equivalent function still exposed in the dylib (presumably this is what libvulkan hooks into). But I imagine it’s still a problem since a number of applications and libraries are built with “vkGetInstanceProcAddr” in mind as that’s what you need to use with libvulkan.

**Comment by SRSaunders** [comment] 2024-01-10 20:03
> Do you mean after device creation, or instance creation?

When I wrote this I actually meant _device_ creation, but on second look you are right, it works after _instance_ creation.

> How were you calling (*vkGetInstanceProcAddr)( m_VulkanInstance, "vkGetDeviceProcAddr" )

I was just shorthanding the explanation.  The actual code looks more like:

```
static const vk::DynamicLoader dl( "libMoltenVK.dylib" );
const PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr =
	dl.getProcAddress<PFN_vkGetInstanceProcAddr>( "vkGetInstanceProcAddr" );
VULKAN_HPP_DEFAULT_DISPATCHER.init( vkGetInstanceProcAddr );

createInstance();	// m_VulkanInstance is defined here

const PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr =
	(PFN_vkGetDeviceProcAddr)(*vkGetInstanceProcAddr)(m_VulkanInstance, "vkGetDeviceProcAddr" );

...

createDevice();

```

Hopefully this more complete code snippet makes better sense.

**Comment by billhollings** [comment] 2024-01-10 22:40
PR #2124 should fix this now. Please test with latest MoltenVK, and close this issue if the problem has been fixed.

**Comment by SRSaunders** [comment] 2024-01-11 02:39
Thank you very much for fixing this for dynamic lookups (`vkGetInstanceProcAddr`), and also for reverting to allowing static linkage for the moment.  This hopefully avoids me having to submit emergency changes for SDK 1.3.275 compatibility.  I can make the changes for dynamic lookups in a more planned way.

One question confirming before I close:  Will the SDK version of MoltenVK still allow for static symbols?  You expressed some doubt about this earlier in the thread. Do you now have confirmation on how MoltenVK is built for the SDK?

**Comment by billhollings** [comment] 2024-01-11 02:52
Yup. LunarG confirmed that the MoltenVK library shipped with the upcoming SDK will expose static links.

**Comment by SRSaunders** [comment] 2024-01-11 03:07
Thanks for confirming.  Closing now.

**Closed** 2024-01-11 03:07 UTC
Labels: Bug, Fixed
