### ISSUE TITLE
Metal buffer alignment is not 256 on iOS arm64 simulator

### ISSUE THREAD

**Issue by LeavesInAutumn** [KhronosGroup/MoltenVK#1989] opened 2023-08-08 11:38 UTC
Hello, I get the following errors when running my app with MoltenVK on iOS arm64 simulator (Apple M1 chips):
```
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:], line 5326: error 'Draw Errors Validation
Vertex Function(VS_Entry_lusion): the offset into the buffer _9 that is bound at buffer index 0 must be a multiple of 256 but was set to 384.
'
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:], line 5326: error 'Draw Errors Validation
Vertex Function(VS_Entry_lusion): the offset into the buffer _9 that is bound at buffer index 0 must be a multiple of 256 but was set to 262336.
'
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:], line 5326: error 'Draw Errors Validation
Vertex Function(VS_Entry_lusion): the offset into the buffer _9 that is bound at buffer index 0 must be a multiple of 256 but was set to 262528.
'
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:], line 5326: error 'Draw Errors Validation
Vertex Function(VS_Entry_lusion): the offset into the buffer _9 that is bound at buffer index 0 must be a multiple of 256 but was set to 192.
```

I've noticed that someone has encountered this problem: https://github.com/KhronosGroup/MoltenVK/issues/1250
And MoltenVK Release note 2021/02/22 said:

> Set Metal buffer alignment to 256 on non-Apple Silicon iOS/tvOS simulators.

But why Apple Silicon iOS simulators do not use alignment as 256 ?

I guess we should always use alignment as 256 on all simulators according to the Apple official documents: https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator?language=objc

> When you set arguments for the render or compute command, align constant buffer offsets to 256 bytes. Normally, iOS requires an alignment of 4 bytes. This difference may mean that you might need to arrange your data differently when running in Simulator.

And if I was wrong, how can I resolve these errors?
Do I need to define any macros to tell MoltenVK the target is arm64 simulator ?

Thanks in advance !

**Comment by billhollings** [comment] 2023-08-14 00:17
PR #1993 fixes this. Please retest with latest MoltenVK and close this issue if the problem is resolved.

**Closed** 2023-10-29 07:14 UTC
Labels: Bug, Fixed
