### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#1208] opened 2021-01-20 13:14 UTC
We are observing that our app's on iOS run significantly slower with the current MoltenVK version, e.g. version ( 1.1.2, spec version 30 ) compared to a previous release ( 1.1.1 spec version 29 ).

Looking at the code differences, I can't see what is causing it, besides the new 'tileBasedDeferredRendering' feature.

Any idea why the latest MoltenVK is so much slower?

**Comment by billhollings** [comment] 2021-01-20 21:18
I'm curious...can you try setting the environment variable `MVK_CONFIG_FAST_MATH_ENABLED=1`, and see if that fixes the issue?

See #1209 for more info.

**Comment by aerofly** [comment] 2021-01-21 09:21
I can confirm that `#   define MVK_CONFIG_FAST_MATH_ENABLED 1` does restore the performance again, even though I do not see where this flag ( fastMathEnabled ) is actually being used?!

**Comment by billhollings** [comment] 2021-01-29 20:58
Closing this as a duplicate of #1209.

**Closed by billhollings** 2021-01-29 20:58 UTC
Labels: Duplicate
