### ISSUE TITLE
Vulkan SDK release feature cut-off Friday Oct 14

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1736] opened 2022-10-09 18:09 UTC
LunarG is planning the next Vulkan SDK release.

A MoltenVK SDK release for this Vulkan SDK will be made Monday Oct 17.

MoltenVK PRs approved by Friday Oct 14 will be included in this release.

@cdavis5e @spnda @HansKristian-Work @richard-lunarg @KarenGhavam-lunarG

**Comment by Gcenx** [comment] 2022-10-09 18:58
Could we have #1735 merged since that resolves a regression before the cutoff.

**Comment by billhollings** [comment] 2022-10-09 19:34
> Could we have #1735 merged since that resolves a regression before the cutoff.

Yup. Definitely planning to bring that change in before the cutoff.

**Comment by billhollings** [comment] 2022-10-10 14:08
> Yup. Definitely planning to bring that change in before the cutoff.

PR #1735 replaced by PR #1738, which has been merged.

**Closed** 2022-10-19 16:49 UTC
Labels: Fixed, SDK Coordination
