### ISSUE TITLE
Support for VK_EXT_pipeline_creation_cache_control

### ISSUE THREAD

**Issue by GPUCode** [KhronosGroup/MoltenVK#1824] opened 2023-01-17 20:14 UTC
This extension is particularly useful for asynchronous pipeline compilation systems and will improve the experience for emulator users like Cemu and Citra. It can also reduce draw time hitching in applications by making vkCreateGraphicsPipeline calls predictable. Most desktop drivers support it nowadays so it would be nice to see it implemented in MoltenVK as well.

**Comment by danginsburg** [comment] 2023-02-23 17:17
I also would like to see this extension.  For us it would be a huge memory savings.  At a high level, here is how we use the VkPipelineCache when that extension is *not* supported:

1. Each rendering thread gets its own VkPipelineCache
2. At startup, we load a main VkPipelineCache from disk, then we do vkMergePipelineCaches to merge any cached shaders to the individual thread caches
3. When needing a new PSO, we create it on the individual thread caches, this is so that there is not lock contention and multiple threads can create PSOs at the sam etime
4. When we exit the game, we merge the individual per-thread caches back to the VkPipelineCache and then write that to disk

The problem is step 2 creates enormous copies in memory in copies of the MVKShaderLibrary that holds the std::string with the shader.

What we do when VK_EXT_pipeline_creation_cache_control is supported saves this memory in the following way:
1. At startup we load the VkPipelineCache from disk
2. When we need to compile a shader, we first call vkCreateGraphicsPipelines with the flag VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT
3. If it fails, then and only then we create the pipeline on the per-thread cache
4. When it’s time to write the VkPipelineCache to disk on exit, we merge the per-thread caches

Since  VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT should be lock free (and also quick) this allows us to avoid duplicating the cache to all of the per-thread caches whilst still having lock free behavior.

**Comment by billhollings** [comment] 2023-02-23 21:21
`VK_EXT_pipeline_creation_cache_control` is fairly easy and straightforward to implement, and we'll proceed to do so.

However, due to the current nature of Metal's pipeline serialization mechanism, it's not clear to what extent there will be large wins with regard to skipping compilations, until Metal makes certain improvements that we have suggested to them.

1) MoltenVK's current pipeline caching serializes pipeline MSL source code out to the cache, which saves the SPIRV-Cross to MSL conversion on recovery. This is one reason why MoltenVK retains the MSL source code internally after a `MTLLibrary` has been created. So the initial implementation of `VK_EXT_pipeline_creation_cache_control` will still trigger both shader and pipeline compilations.

2) The next MoltenVK caching improvement will be to use Metal's binary archives to serialize actual Metal pipelines. Doing so will save Metal pipeline compilation when pulled from the pipeline cache. However, to do so, Metal requires that we have the vertex and fragment shader functions from `MTLLibraries`, in order to look up the pipeline in the binary archive. The problem with this is that Metal provides no mechanism to serialize the `MTLLibrary` itself into binary form (this is something we've requested), which means we will still need to retain the MSL source code, serialize it into the cache, and compile the `MTLLibaries` in order to use them to look up a Metal pipeline in the binary archive.

3) Regarding the MSL source code memory issues, there are a couple of things we can do to improve this. 
    - One is to compress the MSL text when we retain it, which should reduce the memory hit substantially.
    - I've anecdotally noticed that applications sometimes submit the same SPIR-V code to multiple `VKShaderModules`, resulting in the same MSL code, and compilation into multiple identical `MTLLibraries`. To reduce this redundancy, we can create an internal cache that will help eliminate this duplicate MSL source code and `MTLLibraries`.

I propose we approach this in the following steps:

1) Introduce MSL compression and internal caching to alleviate the immediate MSL source code memory pressure.

2) Implement `VK_EXT_pipeline_creation_cache_control`, with the understanding that, for now, it will kick back `VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT` every time a pipeline is pulled from cache.

3) Use Metal binary archives to remove the requirement to perform a pipeline compile when pulling pipelines from the cache (shader compiles will still be required as explained above).

4) Migrate to allowing the SPRIV to MSL conversion to be independent of the pipeline structure (VA's and VB's), so that a SPIRV code will convert to the same MSL, regardless of the pipeline it will be compiled into. This will result in fewer distinct MSL and `MTLLibraries`.

5) If and when Metal supports serializing compiled `MTLLibraries`, introduce this to eliminate the shader compiles as a pipeline is pulled out of the pipeline cache.

**Comment by billhollings** [comment] 2023-02-23 21:37
@danginsburg 

> 3. If it fails, then and only then we create the pipeline on the per-thread cache

If multiple threads try to retrieve the same pipeline, fail, and then create them in their own thread-cache, will each thread end up with copies of essentially the same pipeline? I guess there is no feedback into the global pipeline cache until the merge at the end?

I'm wondering if MoltenVK could internally feed this back to the global pipeline cache? I'm thinking the global cache could mark the failure, and then once a thread compiled the same pipeline, it could feed it back to the global cache, so a subsequent request from a different thread would recover it, rather than compile it again.

Or is it generally the case that only one thread will be interested in any particular pipeline?

**Comment by billhollings** [comment] 2023-02-24 16:01
@danginsburg 

One more question. I guess without the extension, all of the pipeline caches are internally synchronized, but with `VK_EXT_pipeline_creation_cache_control`, you'd set all pipeline caches (including the global one) to be externally synchronized with `VK_PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT_EXT`? Or would you leave the global pipeline cache internally synchronized?

**Comment by danginsburg** [comment] 2023-02-24 16:02
Overall plan sounds good.  A few pieces of feedback:

> However, due to the current nature of Metal's pipeline serialization mechanism, it's not clear to what extent there will be large wins with regard to skipping compilations

Yeah, I'm not expecting wins in terms of skipping compiles, I'm just looking for the big memory savings by not having to duplicate caches across threads.

> I've anecdotally noticed that applications sometimes submit the same SPIR-V code to multiple VKShaderModules, resulting in the same MSL code, and compilation into multiple identical MTLLibraries. To reduce this redundancy, we can create an internal cache that will help eliminate this duplicate MSL source code and MTLLibraries.

For what it's worth, we already de-duplicate VkShaderModules for this reason as a memory optimization (it helped memory consumption on several real Vulkan drivers, including mobile).  From my experience, other Vulkan drivers. do not do this de-duplication.  I don't think it's necessary for MoltenVK to do it either, although I'm not against it as long as it doesn't add much overhead.  

> 1. Introduce MSL compression and internal caching to alleviate the immediate MSL source code memory pressure.

That sounds reasonable, but if it was going to add significantly to PSO creation time I'm not sure I'm in favor of it.  Performance is probably more important than memory here.  The compression would need to be fast (i.e. < 0.1ms), or at least there would need to be an option to disable it.

> If multiple threads try to retrieve the same pipeline, fail, and then create them in their own thread-cache, will each thread end up with copies of essentially the same pipeline? I guess there is no feedback into the global pipeline cache until the merge at the end?

We actually avoid this situation - if two threads encounter the same PSO, only one thread compiles it and the other one waits.  The merge at the end is what gets the individually thread compiled PSOs back into the main archive that gets serialized to disk.

> I'm wondering if MoltenVK could internally feed this back to the global pipeline cache? I'm thinking the global cache could mark the failure, and then once a thread compiled the same pipeline, it could feed it back to the global cache (at this point, it would be a pointer copy, so fast even with locking), so a subsequent request from a different thread would recover it, rather than compile it again.

This is the app's job in my opinion.  I wouldn't add this complexity to MoltenVK.

**Comment by danginsburg** [comment] 2023-02-24 16:05
> One more question. I guess without the extension, all of the pipeline caches are internally synchronized, but with VK_EXT_pipeline_creation_cache_control, you'd set all pipeline caches (including the global one) to be externally synchronized with VK_PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT_EXT? Or would you leave the global pipeline cache internally synchronized?

Actually, at the moment they are all still internally synchronized.  I should probably add VK_PIPELINE_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT_EXT to the individual thread caches so the VK_PIPELINE_CREATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT_EXT doesn't lock, although in practive I've seen this be so fast on drivers it didn't show up much.  I will be keeping the global cache internally synchronized for sure.

**Comment by billhollings** [comment] 2023-02-24 16:16
@danginsburg Thanks for all the feedback. Very helpful. And should simplify things somewhat.

**Comment by billhollings** [comment] 2023-03-07 22:21
Closing based on feedback on PR.

**Closed by billhollings** 2023-03-07 22:21 UTC
Labels: Enhancement, Fixed
