### ISSUE TITLE
Graphics Pipeline creation fails using MSL compiled code

### ISSUE THREAD

**Issue by ifiddynine** [KhronosGroup/MoltenVK#1253] opened 2021-02-10 18:23 UTC
I was just testing use of MSL compiled code to avoid SPIRV -> MSL conversion at runtime, but noticed that it's no longer working. The calls to `vkCreateShaderModule` with MSL binary code prepended with the `kMVKMagicNumberMSLCompiledCode` constant succeeds just fine, but we later get:

`[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Failed to get vertex outputs: SPIRV file too small.`

.. when calling vkCreateGraphicsPipelines. This has worked for us in the past, but we weren't ready to integrate this feature by default. However it's broken in the 1.1.1 release. We'd love to switch to precompiled binary code by default in order to validate the MSL compilation in our build step instead of on app launch which has led to a few bugs sneaking through.

**Comment by billhollings** [comment] 2021-02-11 00:24
Loading MSL code has definitely fallen behind the curve as MoltenVK evolved. 

It is not recommended at this time, until it can be properly addressed.

I'll document that.

**Comment by cdavis5e** [comment] 2021-02-11 00:27
This is a dupe of #956.

**Comment by ifiddynine** [comment] 2021-02-11 12:33
Got it, thanks for the clarification!

**Comment by billhollings** [comment] 2021-02-13 00:29
>I'll document that.

Done. Closing now that documentation is updated, and this is a dup of other issues related to MSL.

**Closed by billhollings** 2021-02-13 00:29 UTC
Labels: Duplicate, Enhancement
