### ISSUE TITLE
MultiSample VK_FORMAT_R32_SINT does not resolve correctly via vkCmdResolveImage on Intel UHD 6xx

### ISSUE THREAD

**Issue by lumonix** [KhronosGroup/MoltenVK#828] opened 2020-02-16 02:24 UTC
Hi,

I believe I have found a bug when trying to use vkCmdResolveImage on a multi-sample R32 INT texture. User error not ruled out either :)

When doing a gpu-> cpu read back of the resolved texture, I don't get any values above 0 back.
(I do appear to be able to get values below 0, but only did limited testing on this).

The same setup works ok on Windows and Linux.
(I've tested Ubuntu 18 with Intel. Redhat 7 with Nvidia card, Window 7/10 with Nvidia cards)

When I switch the texture to multi-sample R32 FLOAT things also work via MoltenVk.
Or if I disable multi-sampling, but keep the R32 INT texture, I also get the correct values when doing the gpu->cpu read back.

I'm using:
Vulkan SDK 1.1.130.0.
MacOs Mojave.
Intel gfx card.

I can privately provide a sample app if you have trouble reproducing this problem.

Thanks!
-Kees

**Comment by billhollings** [comment] 2020-02-16 02:39
@lumonix 

>I can privately provide a sample app if you have trouble reproducing this problem.

That would help. You can send it (or a link to it) to support@brenwill.com and I'll have a look at it.

**Comment by lumonix** [comment] 2020-02-16 15:25
Hi Bill,

I tried another machine with an Geforce 750 in it, which works fine for both the INT32 and F32 msaa buffers.

I believe this problem might be limited to Intel UHD 6xx (Maybe even only Mojave) and thus probably not a MoltenVK bug.

If you are still interested to see it, I've managed to strip down the app enough to publish it here:

https://github.com/lumonix/BugReports/blob/master/repro_bug828_msaa_int_vs_float.zip

The instructions are to run the executable and in the top-left where it says "No renderer" switch to the renderer to see two boxes on screen.

In the float-version you can pick either box.
In the int-version, on Intel, you can only pick the top box.

This is because in the int-version the int32 attachment is either not filled with the correct int-value that uniquely represents each object for picking. Or the read-back is going wrong and we just always get 0 back (or -1 when clicking in empty space).

This seems msaa related since without msaa it also works on Intel.


Feel free to close this bug if you cannot repro or believe with the new info its not a MoltenVk bug (which I believe it isn't, now that I tried other machines)

**Comment by billhollings** [comment] 2020-03-05 21:47
Thanks for submitting your sample app. It helped to figure this out.

The issue appears to be in the attempt to resolve the integer texture.

Metal supports MSAA for most integer formats, but does not support resolving integer formats into single-sample textures. Enabling Metal validation when running your app results in the following assertion appearing:

    `_MTLValidateResolveTexture:340: failed assertion `PixelFormat MTLPixelFormatR32Sint cannot be a MSAA resolve target'`

A Vulkan implementation can inform the app that MSAA is supported for an image format via `VkImageFormatProperties::sampleCounts`, but unfortunately, there doesn't seem to be any way to inform the Vulkan app that it cannot be used as a resolve destination.

However, we should at least add error reporting to MoltenVK to return an error during the creation of a a render pass if it asks for a resolve target with an unresolvable format.

BTW...regarding your picking algorithm, the Vulkan spec says:

>During the resolve the samples corresponding to each pixel location in the source are converted to a single sample before being written to the destination. If the source formats are floating-point or normalized types, the sample values for each pixel are resolved in an implementation-dependent manner. If the source formats are integer types, a single sample’s value is selected for each pixel.

So, even if Metal supported resolving the image, whether you use float or integer formats, the resolved pixel will contain an arbitrary value that might not be an accurate measure of the color from the MSAA pick-painted pixels. For float formats, the resolved value will be a blended value, not necessarily any actual painted value, and for integers, the resolved value will be fairly arbitrary. In both cases, the resolved picked color might not match what was painted.

Is there a reason why you are rendering the scene for picking using MSAA? Might it be better to define the integer-format picking render target as a single-sample image, and avoid resolving it altogether? That way, you'll avoid this issue, and I should think you'll get more accurate results from the pixel-picking. Plus it will likely be a bit more performant.

**Comment by lumonix** [comment] 2020-03-06 15:42
@billhollings thank you for the detailed answer.

Regarding why the pick buffer is multi-sample:

Doesn't Vulkan (like OpenGL) require all color attachments to have the same sample count?
So if I were to make the pick-buffer single-sample, I would have to render twice.

(Which could be an option, just confirming with you I am not missing out on some extension that allows mis-matching sample-count color attachments that MoltenVk also supports)

Thanks!

**Comment by billhollings** [comment] 2020-03-06 16:01
>Doesn't Vulkan (like OpenGL) require all color attachments to have the same sample count?

Yup...that is the case...

>All attachments in `pColorAttachments` that are not `VK_ATTACHMENT_UNUSED` must have the same sample count

I was thinking old-school, where the picking pass would only be rendered interactively as a secondary pass after a user interaction (click, touch, etc).

**Comment by lumonix** [comment] 2020-03-06 16:16
Makes sense. Thanks Bill.

**Comment by billhollings** [comment] 2020-03-26 20:45
> I've left this as a bug until we add error reporting to MoltenVK to return an error during the creation of a a render pass if it asks for a resolve target with an unresolvable format.

PR #843 fixes this to report an error when a `VkFormat` cannot be used as a resolve destination:

```
[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: vkCmdResolveImage(): VK_FORMAT_R32_SINT cannot be used as a resolve destination on this device.
```

**Closed** 2020-03-26 20:45 UTC
Labels: Answered, Bug, Fixed - please test & close

**Comment by kvark** [comment] 2021-12-24 19:57
@billhollings so the solution to this problem was adding an error?
Looks like this is non-conformant behavior from Vulkan point of view. A portability implementation must be able to resolve non-filterable formats like the integer ones, or otherwise we need to work on an additional flag in the portability spec.

**Comment by billhollings** [comment] 2021-12-24 20:59
> otherwise we need to work on an additional flag in the portability spec

Yes. Or for required feature capabilities, we can modify the spec wording itself to say a required format capability is _**not**_ required in the presence of the `VK_KHR_portability_subset` extension.

I'm tracking those kind of proposed spec rewordings [here](https://github.com/KhronosGroup/Vulkan-Portability/issues/24), and platform-specific issues [here](https://github.com/KhronosGroup/Vulkan-Portability/issues/26), although I haven't documented this particular outlier in either of those issues, probably because it hasn't shown up, or been addressed from CTS testing.

**Comment by kvark** [comment] 2021-12-24 23:16
The problem is that Vulkan doesn't have a specific capability for "resolve". Vulkan requires any MSAA texture to be able to resolve. So there is no easy way to just modify the spec wording.
