### ISSUE TITLE
Unable to build Vulkan/X11 on MacOS 

### ISSUE THREAD

**Issue by tnagorran** [KhronosGroup/MoltenVK#1728] opened 2022-09-29 04:22 UTC
Undefined symbols for architecture x86_64:
"_vkCreateXlibSurfaceKHR", referenced from:
_demo_create_surface in <>
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

X11 works on MacOS, it would be nice to add the support for porting old programs

**Comment by cdavis5e** [comment] 2022-09-29 06:37
This is a duplicate of #1694. Unfortunately, it isn't currently feasible to support this the way Xquartz is architected (see [XQuartz#282](/XQuartz/XQuartz/issues/282)).

**Closed by cdavis5e** 2022-09-29 06:37 UTC
