### ISSUE TITLE
Resource leak when using fences?

### ISSUE THREAD

**Issue by gemorin** [KhronosGroup/MoltenVK#103] opened 2018-03-13 23:58 UTC
I have a very simple vulkan test program.  It only displays a triangle (vertices hardcoded in the vertex shader).  Everything is uploaded at https://github.com/gemorin/vulkantest/

The render loop just waits for fences and submits the same command buffers, nothing is modified whatsoever: https://github.com/gemorin/vulkantest/blob/master/vulkantest.cpp#L1014

If I just let this run for a bit, the memory footprint of the process keep on increasing.  If I change the render loop to call vkDeviceWaitIdle() on each loop, the footprint does not increase. 

With the current code when the window is resized, the program calls vkDeviceWaitIdle() before recreating the swap chain and memory usage decreases sharply (before going back up)

This leads me to believe there is some leak in MoltenVk somewhere.

Update: I am using the lunarg vulkansdk 1.0.69 (4effc0d1e38ad3f54179d5ebfc7bb8cd66f0b37983bf8ae88ed5cf8d9174d00a)

**Comment by Hindrik1997** [comment] 2018-03-14 12:20
I can confirm this issue. Saw the same behaviour in my code. What happens to you if you use semaphores instead and don't use vkDeviceWaitIdle()? In my case it deadlocks on vkDeviceWaitIdle(), could you try and see if you have that problem too? 

Also, which version of MoltenVK are you using?

**Comment by gemorin** [comment] 2018-03-14 13:17
Hindrik, I am not 100% sure what you mean by using semaphores instead of vkDeviceWaitIdle().  I am using semaphores along with fences in the render loop and vkDeviceWaitIdle() only during resizing.  

If you're talking about the resizing case only, I *think* you have to call vkDeviceWaitIdle() to make sure nothing is using the resources you are about to destroy (and recreate).

**Comment by Hindrik1997** [comment] 2018-03-14 13:54
@gemorin 
I meant that you should use semaphores to synchronize in your main loop instead of fences. The reason for this is that a fence is a GPU -> CPU sync, so at the start of your renderFrame() you wait on the fence for your previous GPU work to complete. This isn't needed, because an image may already be available to be drawn to (For example, in the case of double buffering). So essentially, you say: GPU, I wait for you. And only after you have submitted the new commandbuffers to the GPU it can start to do more work.

Using semaphores you can keep the GPU busy at all times and the CPU can do so too. (It will block on the vkAqcuireNextImageKHR in case no image is available, in order to let the CPU not go too far ahead)

Semaphores allow you to keep your GPU and your CPU busy. They are similar to fences, except that only the GPU can signal and wait on them. This allows you to keep submitting work to the GPU when it is still busy, in order to keep it busy. It doesn't have to wait anymore on your vkQueueSubmit() call. 

I was indeed talking about the resizing case only, however, I experience deadlocks on vkDeviceWaitIdle() in my resizing function if I do not call vkDeviceWaitIdle() in my render loop. (Before calling vkQueueSubmit). I was wondering if you experience the same issues, because they could be related.

**Comment by gemorin** [comment] 2018-03-14 14:16
@Hindrik1997 My apologies if I am misunderstanding your point but I am guessing you have not looked at my render loop: https://github.com/gemorin/vulkantest/blob/master/vulkantest.cpp#L1016

I am using semaphores the way you describe it along with a fence for synchronization. I believe that you have to use both a fence and semaphores to do if you're reusing the command buffer (which I am doing): https://stackoverflow.com/questions/39599633/why-is-a-vkfence-necessary-for-every-swapchain-command-buffer-when-already-using

I do agree both issues could be related but I am not familiar at all with the MoltenVK code base so it's hard for me to tell.  

Let me know if I am missing anything.

**Comment by Hindrik1997** [comment] 2018-03-14 14:27
@gemorin I actually did see your code. You don't need the fence to reuse you're command buffer. That's where VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT is for. The way you're doing it now causes the CPU to block (thus sync with the GPU) on vkWaitForFences(), which makes the semaphores entirely useless, because you sync with the GPU before you submit new work to it.

**Comment by gemorin** [comment] 2018-03-14 14:49
@Hindrik1997 I see your point now. What you're saying makes sense to me but I am too much of a vulkan newb to be sure.  Let's see what the MoltenVK folks say.

**Comment by billhollings** [comment] 2018-03-14 15:05
@gemorin 

I'm starting to look at this now.

Thanks for providing the sample app.

Where are you sourcing `glfw` from?

**Comment by gemorin** [comment] 2018-03-14 15:36
@billhollings I am using the github current master branch built against the vulkan 1.0.69, i.e
```
git clone https://github.com/glfw/glfw.git
cd glfw
export VULKAN_SDK=PATH/vulkansdk-macos-1.0.69.0
cmake .
make
```
I added one patch for an issue I found (https://github.com/glfw/glfw/issues/1229) but you should not need it to reproduce the problem

**Comment by billhollings** [comment] 2018-03-16 03:02
Fixed by #106.

**Comment by billhollings** [comment] 2018-03-16 19:08
@gemorin 

While working on this, I noticed that your `vulkantest` app exhibits some odd behaviour around rendering synchronization.

When running with MoltenVK built in Debug mode, I noticed the following performance logs:

    [mvk-info] Frame interval: 16.46 ms. Avg frame interval: 8.70 ms. FPS: 114.90. Elapsed time: 20.602 seconds.

Notice the difference between the current frame interval and the average frame interval. This was consistent over time. I temporarily added an extra log entry to capture the frame interval for every render loop, and found the following:

```
[mvk-info] Frame interval: 0.97 ms. Avg frame interval: 7.98 ms. Frame count: 295.
[mvk-info] Frame interval: 14.82 ms. Avg frame interval: 8.60 ms. Frame count: 296.
[mvk-info] Frame interval: 0.81 ms. Avg frame interval: 7.89 ms. Frame count: 297.
[mvk-info] Frame interval: 16.92 ms. Avg frame interval: 8.71 ms. Frame count: 298.
[mvk-info] Frame interval: 0.97 ms. Avg frame interval: 8.01 ms. Frame count: 299.
[mvk-info] Frame interval: 15.71 ms. Avg frame interval: 8.71 ms. Frame count: 300.
[mvk-info] Frame interval: 15.71 ms. Avg frame interval: 8.71 ms. FPS: 114.80. Reporting every: 300 frames. Elapsed time: 27.721 seconds.
[mvk-info] Frame interval: 0.95 ms. Avg frame interval: 8.01 ms. Frame count: 1.
[mvk-info] Frame interval: 15.58 ms. Avg frame interval: 8.69 ms. Frame count: 2.
[mvk-info] Frame interval: 0.95 ms. Avg frame interval: 7.99 ms. Frame count: 3.
[mvk-info] Frame interval: 16.04 ms. Avg frame interval: 8.72 ms. Frame count: 4.
[mvk-info] Frame interval: 1.02 ms. Avg frame interval: 8.02 ms. Frame count: 5.
```
This is likely caused by the fact that your runloop just runs flat out, and is not synchronized to the OS presentation interval, either through the OS, or through Vulkan presentation sychronization. I didn't look into it at all...but you might want to have a closer look at your semaphore and fense use.

I believe that the full-speed nature of your runloop was also what was causing the memory growth. The dispatch thread handling the Vulkan queue submissions was not finding an opportunity to dump the autorelease pool containing the Metal command buffer and encoder objects that accumulate during rendering, because the dispatch thread was never able to fully drain its internal submission queue.

I've fixed the memory growth issue by wrapping each Vulkan queue submission with it's own autorelease pool. However, the unnecessary overload of submissions is still occurring...it is now hidden by the memory cleanups...and based on the timing logs above...I suspect that at least half of them are never actually presented to the screen.

**Comment by Hindrik1997** [comment] 2018-03-16 19:59
@billhollings That's interesting. I saw he used fences to wait for the GPU to complete the work, and then ask for a image and then render to it, and then hand it back to the presentation system.  Yet, I also see some semaphores, which seem to do nothing? How is he getting too many frames then?

What is your proposed way to handle synchronisation with the display regarding MoltenVK? I used 2 semaphores, but I'm having trouble with deadlocks when using MoltenVK, it seems that I have to call vkDeviceQueueIdle() during my render loop. (Right before handing back the image to the presentation system) If I don't, I get a deadlock later on when I call VkDeviceWaitIdle() to resize my swapchain or quit the app. Any idea why this is? See issue #95

**Comment by gemorin** [comment] 2018-03-16 23:38
@billhollings So you're telling me I am not using enough synchronization while @Hindrik1997 is telling me I use too much.  At least you both agree I am doing something wrong :-)

I have to say I am a little surprised by your comment since I am using 2 semaphores plus one fence per swap chain entry in the render loop and that does seem plenty of synchronization to me.

If I comment the vkWaitForFences(), vkResetFences() in the render loop and do not pass the fence to vkQueueSubmit (i.e doing what I think @Hindrik1997 is suggesting: just using 2 semaphores), the program is basically looping (pegged at 100% cpu) and I could see why that could be bad.  But with the current code, it never goes above 4% cpu and I am quite confused what synchronization I could be missing.

Furthermore, what I am doing seems to be mostly in line with these examples
https://www.khronos.org/assets/uploads/developers/library/2016-vulkan-devday-uk/7-Keeping-your-GPU-fed.pdf (Multi-buffering example) and http://asawicki.info/news_1647_vulkan_bits_and_pieces_synchronization_in_a_frame.html

The placement of the vkWaitForFences is a little different in these cases but the difference is basically sleeping waiting mostly on the imageAvailableSem or on the fence. 

Would you care to point out exactly what I am doing wrong?

BTW I've just built MoltenVK with your change and I can confirm that I do not see memory increasing anymore.

**Comment by danginsburg** [comment] 2018-03-26 18:45
I do see the same behavior here in terms of frame interval:

> Notice the difference between the current frame interval and the average frame interval. This was consistent over time. I temporarily added an extra log entry to capture the frame interval for every render loop, and found the following:

However, if I enable presentWithCommandBuffer then I see a more reasonable looking result for Metal locking at 60fps:

```
[mvk-debug] Frame interval: 17.32 ms. Avg frame interval: 16.70 ms. Frame number: 28.
[mvk-debug] Frame interval: 16.17 ms. Avg frame interval: 16.65 ms. Frame number: 29.
[mvk-debug] Frame interval: 16.49 ms. Avg frame interval: 16.63 ms. Frame number: 30.
[mvk-debug] Frame interval: 18.01 ms. Avg frame interval: 16.76 ms. Frame number: 31.
[mvk-debug] Frame interval: 15.17 ms. Avg frame interval: 16.61 ms. Frame number: 32.
[mvk-debug] Frame interval: 16.96 ms. Avg frame interval: 16.65 ms. Frame number: 33.
[mvk-debug] Frame interval: 17.02 ms. Avg frame interval: 16.68 ms. Frame number: 34.
[mvk-debug] Frame interval: 16.26 ms. Avg frame interval: 16.64 ms. Frame number: 35.
[mvk-debug] Frame interval: 16.81 ms. Avg frame interval: 16.66 ms. Frame number: 36.
[mvk-debug] Frame interval: 17.07 ms. Avg frame interval: 16.69 ms. Frame number: 37.
[mvk-debug] Frame interval: 16.30 ms. Avg frame interval: 16.66 ms. Frame number: 38.
[mvk-debug] Frame interval: 16.59 ms. Avg frame interval: 16.65 ms. Frame number: 39.
[mvk-debug] Frame interval: 17.73 ms. Avg frame interval: 16.75 ms. Frame number: 40.
[mvk-debug] Frame interval: 15.69 ms. Avg frame interval: 16.65 ms. Frame number: 41.
[mvk-debug] Frame interval: 16.60 ms. Avg frame interval: 16.65 ms. Frame number: 42.
[mvk-debug] Frame interval: 17.62 ms. Avg frame interval: 16.74 ms. Frame number: 43.
[mvk-debug] Frame interval: 15.83 ms. Avg frame interval: 16.66 ms. Frame number: 44.
[mvk-debug] Frame interval: 16.55 ms. Avg frame interval: 16.65 ms. Frame number: 45.
[mvk-debug] Frame interval: 17.77 ms. Avg frame interval: 16.75 ms. Frame number: 46.
[mvk-debug] Frame interval: 15.56 ms. Avg frame interval: 16.64 ms. Frame number: 47.
[mvk-debug] Frame interval: 16.64 ms. Avg frame interval: 16.64 ms. Frame number: 48.
[mvk-debug] Frame interval: 17.72 ms. Avg frame interval: 16.74 ms. Frame number: 49.
[mvk-debug] Frame interval: 15.91 ms. Avg frame interval: 16.66 ms. Frame number: 50.
[mvk-debug] Frame interval: 16.60 ms. Avg frame interval: 16.66 ms. Frame number: 51.
[mvk-debug] Frame interval: 17.53 ms. Avg frame interval: 16.74 ms. Frame number: 52.
```

We have seem back frame skipping when not using the presentWithCommandBuffer path so I disabled it in dota.  This is maybe a clue.  I wonder if there is some missing synchronization, but I'm not sure.  I would need to dig into it more.

**Comment by billhollings** [comment] 2018-03-30 23:30
PR #118 now sets `presentWithCommandBuffer` to `true` by default.

**Closed by billhollings** 2018-03-30 23:30 UTC
Labels: bug, fixed - please test & close, help wanted
