### ISSUE TITLE
Distorted cubemap texture coordinates

### ISSUE THREAD

**Issue by TheSpydog** [KhronosGroup/MoltenVK#1205] opened 2021-01-16 19:38 UTC
Games that use the [FNA3D](https://github.com/FNA-XNA/FNA3D) graphics library with MoltenVK are exhibiting some odd distortion behavior with cubemap texture coordinates.

Here is an example application with a simple skybox: http://moonside.games/files/SkyboxTest.zip To run the application:
```
cd CubemapBug
chmod +x ./KavTest
DYLD_LIBRARY_PATH=./osx FNA3D_FORCE_DRIVER=Vulkan ./KavTest
```
Use the IJKL keys to look around. Turn the camera toward the sky and to the right to see the distortion. When running with Vulkan it looks like:
<img width="752" alt="vulkan-pic" src="https://user-images.githubusercontent.com/8942401/104820204-50476580-5801-11eb-99f0-0d283a199ba6.png">
Whereas with Metal or OpenGL, it looks like:
<img width="752" alt="metal-pic" src="https://user-images.githubusercontent.com/8942401/104820222-6a814380-5801-11eb-97f4-44cb09e8c85b.png">

This behavior has only been observed with MoltenVK. On Windows and Linux with AMD/NVIDIA Vulkan drivers, the cubemaps are rendered correctly. FNA3D has been rigorously tested for Vulkan spec compliance, and the affected applications do not trigger any Vulkan validation errors, so this seems like an MVK bug.

If you want to run the sample with a different graphics backend, you can set the `FNA3D_FORCE_DRIVER` environment variable to OpenGL or Metal. This is particularly useful if you want to compare side-by-side captures of the app when running with MoltenVK vs. Metal.

cc: @flibitijibibo @thatcosmonaut

**Comment by flibitijibibo** [comment] 2021-02-16 19:53
We dug into this and verified that it was Intel-specific - here is a simplified test case:

http://flibitijibibo.com/mvkCubemap.tar.bz2

Simply extract and `./RunVulkan`. The FNA3D binary is modified to prefer integrated over discrete, which should make it a little easier to test on hybrid setups.

**Comment by cdavis5e** [comment] 2021-02-16 20:05
I'd found a similar problem with using gradient sampling on a cube map running the Vulkan test suite. At the time, I had thought it were a problem with the Metal driver, but maybe it's a bug in MoltenVK or SPIRV-Cross. Running your reproducer may shed light on that.

**Comment by cdavis5e** [comment] 2021-02-16 20:11
Hmm, I don't see anything obviously wrong with the MSL that MoltenVK produces from the supplied SPIR-V. How do I get FNA to dump the shader it supplies? I want to see what's different with the Metal backend.

**Comment by flibitijibibo** [comment] 2021-02-16 20:18
New FNA3D binary...

[mtlDump.zip](https://github.com/KhronosGroup/MoltenVK/files/5991440/mtlDump.zip)

There's no easy way to dump the MojoShader parse data, so I just modified the Metal backend to spit out every shader it compiles. For this sample we save the Vulkan pipeline cache to `FNA3D_Vulkan_PipelineCache.blob`.

**Comment by cdavis5e** [comment] 2021-02-20 23:42
I don't see anything different between the fragment shaders generated. This leads me to suspect there's something wrong with the geometry. And it does look a bit wonky in the demo.

**Comment by flibitijibibo** [comment] 2021-02-21 00:24
I'll have to agree with that... aside from the swizzle helpers the shaders are virtually  identical, so it may be a case where the vertex data gets messed up for the Intel driver specifically. The data passed through FNA3D is identical across backends, so it would have to be the input layout I guess?

**Comment by cdavis5e** [comment] 2021-02-22 06:13
I think I know what might be wrong. I think it has to do with how normalized device coordinates are handled.

In Vulkan, the (x, y) coordinates increase *down* and to the right--and fragment shaders must reflect this by setting the `OriginUpperLeft` mode--while in Metal, coordinates increase *up* and to the right. To account for this, MoltenVK inserts a line in the vertex shader to negate the y coordinate. I'm wondering if this transform is somehow triggering this.

I say this because I see no such transform in the shaders used by FNA. How does it handle this difference?

**Comment by flibitijibibo** [comment] 2021-02-22 12:49
FNA3D uses the D3D coordinate system, so the Metal renderer just passes through with no coordinate system changes. For Vulkan we use KHR_maintenance1 to flip, and OpenGL flips with the same vertex shader idea.

**Comment by cdavis5e** [comment] 2021-02-22 17:18
> For Vulkan we use KHR_maintenance1 to flip,

I wonder if Intel's drivers aren't handling the negative viewport height correctly here.

**Comment by flibitijibibo** [comment] 2021-02-22 18:00
Possibly! This is about where my Metal experience fizzles out; the shader seems to be doing the right thing but I don't know how sensitive MSL is compared to the old GLSL issues we used to fight. The way we flip in GL, we have a `uniform float vpFlip` that's always either 0 or 1, and we do `gl_Position.y = gl_Position.y * vpFlip;` so we can handle both backbuffer and framebuffer rendering without recompiling anything. Pretty much any attempt to make it smarter resulted in platform- and driver-specific failures >_<

This probably isn't worth the added overhead, but I could see a similar idea being done but reacting specifically to the KHR_maintenance1 extension - that is, when height is negative it flips the VK viewport back to normal coordinates when encoding to Metal and skipping the inversion in the vertex shader. (Just typing that out felt like more work than it's worth...)

**Comment by flibitijibibo** [comment] 2021-02-24 05:13
Using a hacked pipeline cache I was able to confirm the bug is related to the viewport. My process:

- Run the sample as-is
- Open up FNA3D_Vulkan_PipelineCache.blob with vim, `/Invert` to go to the flip lines, replace `out.gl_Position` with `//t.gl_Position`
- Apply this FNA3D patch...

```
diff --git a/src/FNA3D_Driver_Vulkan.c b/src/FNA3D_Driver_Vulkan.c
index 70deaf4..85dfc65 100644
--- a/src/FNA3D_Driver_Vulkan.c
+++ b/src/FNA3D_Driver_Vulkan.c
@@ -123,8 +123,8 @@ static const VkComponentMapping RGBA_SWIZZLE =
 static const uint8_t DEVICE_PRIORITY[] =
 {
        0,      /* VK_PHYSICAL_DEVICE_TYPE_OTHER */
-       3,      /* VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU */
-       4,      /* VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU */
+       4,      /* VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU */
+       3,      /* VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU */
        2,      /* VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU */
        1       /* VK_PHYSICAL_DEVICE_TYPE_CPU */
 };
@@ -5981,9 +5981,9 @@ static void VULKAN_INTERNAL_SetViewportCommand(VulkanRenderer *renderer)
 
        /* Flipping the viewport for compatibility with D3D */
        vulkanViewport.x = (float) renderer->viewport.x;
-       vulkanViewport.y = (float) (renderer->viewport.y + renderer->viewport.h);
+       vulkanViewport.y = (float) (renderer->viewport.y);// + renderer->viewport.h);
        vulkanViewport.width = (float) renderer->viewport.w;
-       vulkanViewport.height = (float) -renderer->viewport.h;
+       vulkanViewport.height = (float) renderer->viewport.h;
        vulkanViewport.minDepth = renderer->viewport.minDepth;
        vulkanViewport.maxDepth = renderer->viewport.maxDepth;

```

... and suddenly, Intel works!

**Comment by cdavis5e** [comment] 2021-02-24 05:56
As I thought. This means it's a bug in the Metal driver. Would you like to file a feedback, or do you want me to do it?

**Comment by flibitijibibo** [comment] 2021-02-24 10:02
I'm not able to myself, so if you are that'd be great!

**Comment by billhollings** [comment] 2021-02-24 14:24
>This means it's a bug in the Metal driver.

It this something we want to workaround in MoltenVK in the meantime? Or would it be too unpredictable to know when to apply it?

**Comment by cdavis5e** [comment] 2021-02-24 19:24
> > This means it's a bug in the Metal driver.
> 
> It this something we want to workaround in MoltenVK in the meantime? Or would it be too unpredictable to know when to apply it?

There's only one limited circumstance where we could apply the workaround that @flibitijibibo described: when viewports are not dynamic state and *all* of them have negative viewport height. When some have it and some don't, or if viewports are dynamic state, then we can't apply it, because we can't predict at pipeline compile time whether or not a viewport with a negative height will be used. Heck, we can't even do that at encode time, so compiling multiple pipelines is out, too. I don't think it's worth trying to work around this.

**Comment by cdavis5e** [comment] 2021-02-27 22:22
Filed FB9022749. Sorry about the delay. I'm working on 3 or 4 different things at once right now.

**Comment by flibitijibibo** [comment] 2021-02-27 22:40
Excellent, thanks so much for checking this out!

**Comment by flibitijibibo** [comment] 2021-03-29 03:59
We have a new trace! Terrifyingly it's not a cubemap this time, it's a regular 2D texture. This file works with the mvkCubemap sample from before:

[FNA3D_Trace-skewed-texture-tiling.zip](https://github.com/KhronosGroup/MoltenVK/files/6219107/FNA3D_Trace-skewed-texture-tiling.zip)

You will see that the tiling of the background texture at the end of the trace is heavily repeated instead of stretched across the viewport. As with the previous trace, hacking the pipeline cache and ignoring viewport flips in the renderer fixes the issue. On the bright side, we also discovered that `MVK_CONFIG_SHADER_CONVERSION_FLIP_VERTEX_Y=1` also works, and for our purposes this is enough to get us back on our feet for Vulkan as the default on macOS.

**Comment by billhollings** [comment] 2022-03-11 16:47
Since we've resolved that this is not inherently fixable in MoltenVK, and an app can workaround for Intel Metal drivers, I'm going to remove this as a MoltenVK bug, mark it as a discussion, and close it.

**Closed by billhollings** 2022-03-11 16:47 UTC
Labels: Answered, Information, Metal improvement required
