### ISSUE TITLE
Push constants don't seem to work

### ISSUE THREAD

**Issue by 741g** [KhronosGroup/MoltenVK#327] opened 2018-11-01 04:59 UTC
[mvk-debug] Performance to convert SPIR-V to MSL source code curr: 2.495 ms, avg: 2.495 ms, min: 2.495 ms, max: 2.495 ms, count: 1
    [mvk-info] Converting SPIR-V:
    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 7
    ; Bound: 43
    ; Schema: 0
                   OpCapability Shader
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Vertex %4 "main" %10 %15 %25 %42
                   OpSource GLSL 450
                   OpSourceExtension "GL_ARB_separate_shader_objects"
                   OpName %4 "main"
                   OpName %8 "gl_PerVertex"
                   OpMemberName %8 0 "gl_Position"
                   OpName %10 ""
                   OpName %15 "pos"
                   OpName %25 "color_varying"
                   OpName %27 "TransformPC"
                   OpMemberName %27 0 "mvp"
                   OpName %29 "transformPC"
                   OpName %39 "Transform"
                   OpMemberName %39 0 "mvp"
                   OpName %41 "transform"
                   OpName %42 "color"
                   OpMemberDecorate %8 0 BuiltIn Position
                   OpDecorate %8 Block
                   OpDecorate %15 Location 0
                   OpDecorate %25 Location 0
                   OpMemberDecorate %27 0 ColMajor
                   OpMemberDecorate %27 0 Offset 0
                   OpMemberDecorate %27 0 MatrixStride 16
                   OpDecorate %27 Block
                   OpMemberDecorate %39 0 ColMajor
                   OpMemberDecorate %39 0 Offset 0
                   OpMemberDecorate %39 0 MatrixStride 16
                   OpDecorate %39 Block
                   OpDecorate %41 DescriptorSet 0
                   OpDecorate %41 Binding 0
                   OpDecorate %42 Location 1
              %2 = OpTypeVoid
              %3 = OpTypeFunction %2
              %6 = OpTypeFloat 32
              %7 = OpTypeVector %6 4
              %8 = OpTypeStruct %7
              %9 = OpTypePointer Output %8
             %10 = OpVariable %9 Output
             %11 = OpTypeInt 32 1
             %12 = OpConstant %11 0
             %13 = OpTypeVector %6 2
             %14 = OpTypePointer Input %13
             %15 = OpVariable %14 Input
             %17 = OpConstant %6 0
             %18 = OpConstant %6 1
             %22 = OpTypePointer Output %7
             %24 = OpTypePointer Output %13
             %25 = OpVariable %24 Output
             %26 = OpTypeMatrix %7 4
             %27 = OpTypeStruct %26
             %28 = OpTypePointer PushConstant %27
             %29 = OpVariable %28 PushConstant
             %30 = OpTypePointer PushConstant %26
             %39 = OpTypeStruct %26
             %40 = OpTypePointer Uniform %39
             %41 = OpVariable %40 Uniform
             %42 = OpVariable %14 Input
              %4 = OpFunction %2 None %3
              %5 = OpLabel
             %16 = OpLoad %13 %15
             %19 = OpCompositeExtract %6 %16 0
             %20 = OpCompositeExtract %6 %16 1
             %21 = OpCompositeConstruct %7 %19 %20 %17 %18
             %23 = OpAccessChain %22 %10 %12
                   OpStore %23 %21
             %31 = OpAccessChain %30 %29 %12
             %32 = OpLoad %26 %31
             %33 = OpLoad %13 %15
             %34 = OpCompositeExtract %6 %33 0
             %35 = OpCompositeExtract %6 %33 1
             %36 = OpCompositeConstruct %7 %34 %35 %17 %18
             %37 = OpMatrixTimesVector %7 %32 %36
             %38 = OpVectorShuffle %13 %37 %37 0 1
                   OpStore %25 %38
                   OpReturn
                   OpFunctionEnd
    
    End SPIR-V
    
    Converted MSL:
    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct TransformPC <----------------this used to be layout(push_constant)
    {
        float4x4 mvp;
    };
    
    struct Transform
    {
        float4x4 mvp;
    };
    
    struct main0_out
    {
        float2 color_varying [[user(locn0)]];
        float4 gl_Position [[position]];
    };
    
    struct main0_in
    {
        float2 pos [[attribute(0)]];
    };
    
    vertex main0_out main0(main0_in in [[stage_in]], constant TransformPC& transformPC [[buffer(1)]])
    {
        main0_out out = {};
        out.gl_Position = float4(in.pos, 0.0, 1.0);
        out.color_varying = (transformPC.mvp * float4(in.pos, 0.0, 1.0)).xy;
        out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
        return out;
    }
    
    
    End MSL
    
    Estimated original GLSL:
    #version 450
    
    layout(binding = 0, std140) uniform Transform
    {
        mat4 mvp;
    } transform;
    
    struct TransformPC
    {
        mat4 mvp;
    };
    
    uniform TransformPC transformPC; <--------------estimated back to being a normal uniform
    
    layout(location = 0) in vec2 pos;
    layout(location = 0) out vec2 color_varying;
    layout(location = 1) in vec2 color;
    
    void main()
    {
        gl_Position = vec4(pos, 0.0, 1.0);
        color_varying = (transformPC.mvp * vec4(pos, 0.0, 1.0)).xy;
    }
    
    
    End GLSL
    
    
    [mvk-debug] Performance to compile MSL source code into a MTLLibrary curr: 0.392 ms, avg: 1.339 ms, min: 0.392 ms, max: 2.287 ms, count: 2
    [mvk-debug] Performance to retrieve shader library from the cache curr: 23.146 ms, avg: 23.146 ms, min: 23.146 ms, max: 23.146 ms, count: 1
    [mvk-debug] Performance to retrieve a MTLFunction from a MTLLibrary curr: 0.007 ms, avg: 0.007 ms, min: 0.007 ms, max: 0.007 ms, count: 1
    [mvk-debug] Performance to convert SPIR-V to MSL source code curr: 0.765 ms, avg: 1.630 ms, min: 0.765 ms, max: 2.495 ms, count: 2
    [mvk-info] Converting SPIR-V:
    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 7
    ; Bound: 24
    ; Schema: 0
                   OpCapability Shader
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Fragment %4 "main" %9 %12
                   OpExecutionMode %4 OriginUpperLeft
                   OpSource GLSL 450
                   OpSourceExtension "GL_ARB_separate_shader_objects"
                   OpName %4 "main"
                   OpName %9 "fragcolor"
                   OpName %12 "color_varying"
                   OpDecorate %9 Location 0
                   OpDecorate %12 Location 0
              %2 = OpTypeVoid
              %3 = OpTypeFunction %2
              %6 = OpTypeFloat 32
              %7 = OpTypeVector %6 4
              %8 = OpTypePointer Output %7
              %9 = OpVariable %8 Output
             %10 = OpTypeVector %6 2
             %11 = OpTypePointer Input %10
             %12 = OpVariable %11 Input
             %13 = OpTypeInt 32 0
             %14 = OpConstant %13 0
             %15 = OpTypePointer Input %6
             %18 = OpConstant %6 0.200000003
             %19 = OpConstant %13 1
             %22 = OpConstant %6 1
              %4 = OpFunction %2 None %3
              %5 = OpLabel
             %16 = OpAccessChain %15 %12 %14
             %17 = OpLoad %6 %16
             %20 = OpAccessChain %15 %12 %19
             %21 = OpLoad %6 %20
             %23 = OpCompositeConstruct %7 %17 %18 %21 %22
                   OpStore %9 %23
                   OpReturn
                   OpFunctionEnd
    
    End SPIR-V
    
    Converted MSL:
    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct main0_out
    {
        float4 fragcolor [[color(0)]];
    };
    
    struct main0_in
    {
        float2 color_varying [[user(locn0)]];
    };
    
    fragment main0_out main0(main0_in in [[stage_in]])
    {
        main0_out out = {};
        out.fragcolor = float4(in.color_varying.x, 0.2, in.color_varying.y, 1.0);
        return out;
    }
    
    
    End MSL
    
    Estimated original GLSL:
    #version 450
    
    layout(location = 0) out vec4 fragcolor;
    layout(location = 0) in vec2 color_varying;
    
    void main()
    {
        fragcolor = vec4(color_varying.x, 0.2, color_varying.y, 1.0);
    }
    
    
    End GLSL
    
    
    [mvk-debug] Performance to compile MSL source code into a MTLLibrary curr: 0.560 ms, avg: 1.080 ms, min: 0.392 ms, max: 2.287 ms, count: 3
    [mvk-debug] Performance to retrieve shader library from the cache curr: 28.208 ms, avg: 25.677 ms, min: 23.146 ms, max: 28.208 ms, count: 2
    [mvk-debug] Performance to retrieve a MTLFunction from a MTLLibrary curr: 0.002 ms, avg: 0.005 ms, min: 0.002 ms, max: 0.007 ms, count: 2
    [mvk-debug] Performance to compile MTLFunctions into a pipeline curr: 1.009 ms, avg: 1.009 ms, min: 1.009 ms, max: 1.009 ms, count: 1
    initialize: created graphics pipeline
    initialize: created command buffers
    initialize: uploaded vertex data

**Comment by billhollings** [comment] 2018-11-07 01:35
@741g 

Can you clarify what you mean when you say _"Push constants don't seem to work"_?

The MSL shader conversion does not seem to be showing anything obviously incorrect. The `transformPC` variable is being passed as buffer index 1 in MSL and is accessed by the shader...and based on your log...the shader seems to be compiling.

What specifically is not working in your app?

**Comment by 741g** [comment] 2018-11-07 01:40
A rotation matrix is applied to transformPC every frame, but I don't see the colors rotating. vkCmdPushConstants is used to send the matrix over.

**Comment by billhollings** [comment] 2018-11-07 02:32
Hmmm...push constants are fairly common...and this is the first I've heard of them not working.

You can try push constants out via the _Sascha Willems_ samples. You can find a version that is compatible and tested against MoltenVK [here](https://github.com/brenwill/Vulkan). The [`Demos/README.md`](https://github.com/KhronosGroup/MoltenVK/blob/master/Demos/README.md#sascha-willems-install) document in the MoltenVK repo explains how to install these samples.

If you continue to have trouble after investigating further...and are able to ZIP up a small _Xcode_ project that demonstrates the issue...upload it to somewhere like Dropbox and post a link back here so we can evaluate it.

**Comment by 741g** [comment] 2018-11-07 04:18
Ok, I'll try to corral it into a minimal example. However, what seems to be happening is that the colors are not animating at all (plus not being interpolated: see https://github.com/KhronosGroup/MoltenVK/issues/328)

![image](https://user-images.githubusercontent.com/32140436/48110431-eda9b680-e200-11e8-994e-bf69ddcc0983.png)

(and it freezes with those colors, which makes me think push constants are not working)

Intended look (and this is what it looks like on libportability and on Linux/Windows NVIDIA Vulkan drivers):

![image](https://user-images.githubusercontent.com/32140436/48110440-00bc8680-e201-11e8-8cbe-0c3d15aed66f.png)

sequence of calls:

https://android-review.googlesource.com/c/platform/external/qemu/+/803202/16/android/android-emugl/host/libs/libOpenglRender/samples/HelloVulkan.cpp

**Comment by billhollings** [comment] 2018-11-07 05:44
Thanks for clarifying what you are looking for...and that it works correctly on other Vulkan implementations.

Unfortunately the call sequence is clearly tied to a specific implementation class structure. And there seems to be a mix of GL and VK framework artifacts. It doesn't look like the calls can simply be copied out and pasted into another demo app.

How are you building this? Is there an Xcode project...or a set of CPP files...you can send that we can incorporate into a demo here?

**Comment by billhollings** [comment] 2018-11-07 05:57
Thanks for clarifying what you are looking for...and that it works correctly on other Vulkan implementations.

Unfortunately the call sequence is clearly tied to a specific implementation class structure. And there seems to be a mix of GL and VK framework artifacts. It doesn't look like the calls can simply be copied out and pasted into another demo app.

How are you building this? Is there an Xcode project...or a set of CPP files...you can send that we can incorporate into a demo here?

**Comment by billhollings** [comment] 2018-11-09 12:52
Since the fragment shader is shading floats in the range 0.0-1.0...the effect you are seeing is almost as if the rendering is being done to a texture with only 1 bit per color component (each color component is either completely on or off).

Very strange.

If you are able to post the the full sample project so we can explore what's going on...that would be helpful.

**Comment by billhollings** [comment] 2019-01-16 19:32
@741g Were you able to resolve this...or put together a sample app that you can post so we can try to figure out the issue?

**Comment by hrydgard** [comment] 2019-07-09 12:32
I don't currently have a repro I can share, but I also have an issue with push constants in MoltenVK.

Here's a sketch what appears to be happening:

vkBindPipeline(pipe1)
vkBindDescriptorSet(pipe1, a uniform buffer in set 0, binding 0)
vkPushConstants(constants1)
vkDraw(draw1)
vkPushConstants(constants2)
vkDraw(draw2)
vkBindPipeline(pipe2)
vkPushConstants(constants3)
vkDraw(draw3)
```

It appears that draw3 sees constants2 instead of constants3, which badly breaks rendering.

**Comment by hrydgard** [comment] 2019-07-09 12:40
Found it. The issue is that if you don't do a vkCmdBindDescriptorSets after binding a new pipeline, push constants are broken. Doing an empty     
```
        device.cmd_bind_descriptor_sets(
                command_buffer,
                vk::PipelineBindPoint::GRAPHICS,
                self.pipeline_layout,
                0,
                &[],
                &[],
            );
```
fixes things right up.

Unfortunately the validation layers complain about this, so a fix in MoltenVK would be much better.

**Comment by hrydgard** [comment] 2019-07-09 12:56
https://github.com/KhronosGroup/MoltenVK/blob/a5cefa5c98a6c1a80bb52a55a189dcbb7b1cfdb0/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L56

It seems that push constant destination is only updated after binddescriptorset, so if you are switching to a pipeline that is not using any descriptor sets, these don't get updated and vkCmdPushConstants has no effect.

**Comment by hrydgard** [comment] 2019-07-09 20:28
@billhollings The original poster here talks about an apparent shader generation issue, which is probably not the same push constant problem I found - should I break out my reports into a separate issue? There is a real bug in MoltenVK here that should be looked at.

**Comment by billhollings** [comment] 2019-07-09 20:57
@hrydgard Yes, please. We can then put a separate bug label on it to keep a focus on it.

And please make the title a bit more specific while you're at it. To make it easier...just consolidate your 3 comments into a single one.

**Comment by hrydgard** [comment] 2019-07-10 07:32
Done, #657.

**Comment by billhollings** [comment] 2019-07-10 14:09
@hrydgard Thanks. 

Closing this issue since the original issue is not sufficiently defined yet.

**Closed by billhollings** 2019-07-10 14:09 UTC
Labels: requested more info
