### ISSUE TITLE
Segfault/OOB in `MVKDescriptorSet.mm`

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [KhronosGroup/MoltenVK#1752] opened 2022-10-27 13:07 UTC
I am getting a segfault in `MVKDescriptorSet.mm` at line 307-11
![Screenshot 2022-10-27 at 14 02 49](https://user-images.githubusercontent.com/80696589/198291797-fb354e79-8271-4103-9682-0f6e6dde0715.png)

From a little poking around it looks like `descIdx` ends up being `17` (w/ `descStartIdx` of `1`) whilst `_descriptors.size()` is only `17` - resulting in an OOB and then a segfault as the read descriptor ends up being `NULL`. The same descriptor code seems to work fine on Linux and Windows aswell but I don't really have enough context into the issue rn to say whether it's MVKs fault or just the application being broken.

Is it possible that there could be some more validation/checks around descriptors to prevent this from just segfaulting? It has made it rather difficult to debug.

Sorry that this isn't terribly well phrased - I'm not über familiar with graphics APIs.

**Comment by Th3T3chn0G1t** [comment] 2022-10-29 12:28
Forgot to note that this is with validation layers

**Comment by billhollings** [comment] 2022-10-31 18:54
Thanks for digging into the cause.

Based on the info you provided, yes a `descStartIdx` of `1` and a `descriptorCount` of `17` would cause an OOB here, if there are no consecutive bindings beyond those. 

The spec [requires](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-dstArrayElement-00321) the app to take this into consideration:

> The sum of dstArrayElement and descriptorCount must be less than or equal to the number of array elements in the descriptor set binding specified by dstBinding, and all applicable consecutive bindings, as described by [consecutive binding updates](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-updates-consecutive)

MoltenVK follows the Vulkan guidelines that the driver should do as little validation as possible, and leaves most validation to the validation layers, including most array bounds checks.

PR #1754 fixes this particular OOB crash, by silently ignoring descriptor update values beyond the bounds. Please test with that PR, or master once it's pulled in, and close this issue if it fixes the problem you encountered.

This is a validation breach as well, so you should also consider posting a bug to the [Vulkan SDK issues list](https://vulkan.lunarg.com/issue/home).

**Comment by Th3T3chn0G1t** [comment] 2022-10-31 19:43
Does seem to be fixed with that patch thank you!

**Closed** 2022-10-31 21:11 UTC
Labels: Fixed
