### ISSUE TITLE
Function specialization leads to Metal shader leaks.

### ISSUE THREAD

**Issue by kuwerty** [KhronosGroup/MoltenVK#746] opened 2019-09-29 13:49 UTC
I have an application using vkCreateGraphicsPipelines once per frame and then destroys the pipeline once the command buffer has finished executing. Not ideal, but it seems to expose a resource leak.

The fragment shader is the same on each frame but is specialized with VkSpecializationInfo passed to vkCreateGraphicsPipelines. However the vertex and fragment shaders are the same on each call.

After running N frames and running a Metal frame capture (in Xcode) I'm seeing N fragment functions in the Xcode GPU resource view. There doesn't seem to be any upper limit to the number of Metal fragment functions created (there can be 1000s of them if the app is left running).

This doesn't seem happen when the function is not specialized.

FWIW all the Metal shader source code that you can see after clicking one of the fragment function looks to be the same.

Using the LunarG 1.1.121.1 SDK:
0934e3216f30534c7d3cb67414f1ebe8230846af : https://github.com/KhronosGroup/MoltenVK.git

**Comment by billhollings** [comment] 2019-10-05 20:46
@kuwerty 

I am unable to replicate this as you describe. Repeatedly creating multiple shader specializations, and/or multiple graphics pipelines using those shader specializations does not result in excess fragment functions in the _All Resources_ pane of a GPU trace.

However...I was able to see excess specialized fragment functions if I did not destroy the graphic pipeline objects when creating new ones. By doing that, the old graphics pipelines are leaked and the specialized shader functions contained within those leaked graphics pipelines then appear in the _All Resources_ pane of the GPU trace.

Can you verify that the `vkDestroyPipeline()` function in MoltenVK is actually being invoked to destroy the old graphics pipelines, please?

**Comment by kuwerty** [comment] 2019-10-07 14:42
@billhollings The vkDestroyPipeline function was being called and it's destroying the same objects it created on each frame. 

With MVK_CONFIG_TRACE_VULKAN_CALLS=1 the main loop repeats as below.

Let me try and get one of the mvk demo apps to do the same thing.

[mvk-trace] vkAcquireNextImageKHR()
[mvk-trace] vkBeginCommandBuffer()
[mvk-trace] vkCreateRenderPass()
[mvk-trace] vkCreateFramebuffer()
[mvk-trace] vkCmdBeginRenderPass()
[mvk-trace] vkAllocateDescriptorSets()
[mvk-trace] vkUpdateDescriptorSets()
[mvk-trace] vkCmdBindDescriptorSets()
[mvk-trace] vkGetPhysicalDeviceFormatProperties()
[mvk-trace] vkGetPhysicalDeviceFormatProperties()
[mvk-trace] vkGetPhysicalDeviceFormatProperties()
[mvk-trace] vkCreateGraphicsPipelines()
[mvk-trace] vkCmdBindPipeline()
[mvk-trace] vkCmdBindVertexBuffers()
[mvk-trace] vkCmdDraw()
[mvk-trace] vkCmdEndRenderPass()
[mvk-trace] vkEndCommandBuffer()
[mvk-trace] vkQueueSubmit()
[mvk-trace] vkQueuePresentKHR()
[mvk-trace] vkWaitForFences()
[mvk-trace] vkResetCommandPool()
[mvk-trace] vkResetCommandBuffer()
[mvk-trace] vkResetDescriptorPool()
[mvk-trace] vkResetFences()
[mvk-trace] vkDestroyPipeline()
[mvk-trace] vkDestroyRenderPass()
[mvk-trace] vkDestroyFramebuffer()
<repeats>

**Comment by kuwerty** [comment] 2019-10-07 15:58
It's not clear to me why the 'newMTLRenderPipelineState' function here:

https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L1752

Does a retain before returning the pipeline state.

After debugging it with xcode: completion handler passes an object with refcount of 1. The compileComplete function takes the retain count to 2.  But the final retain count of the returned _mtlRenderPipelineState is 3. The destructor ~MVKRenderPipelineCompiler gets that down to 2. But I only see 1 other release ~MVKGraphicsPipeline and I'm not seeing a _mtlPipelineState ever getting completely released (specialized or not).

I've put a breakpoint in MVKGraphicsPipeline::~MVKGraphicsPipeline() and just before 	[_mtlPipelineState release] I can see:
(lldb) p (int)CFGetRetainCount(_mtlPipelineState)
(int) $3 = 2

**Comment by billhollings** [comment] 2019-10-07 19:45
@kuwerty 

Thanks for delving into the code in your testing.

>Does a retain before returning the pipeline state...etc.

I noticed that sequence too during my investigation..and agree with your assessment of the bonus retain. But in my testing, the eventual retain count works out.

Same thing with the handling of the specialized `MTLFunction` in `MVKFunctionSpecializer`.

Now that you've confirmed you call sequence...I'm wondering if this is an autorelease issue. My testing used a specialization demo that uses standard Apple threading runloops...containing implicit autorelease pools.

Does your code use a different threading model?

If so...it might be that then original specialized `MTLFunction` and/or `MTLRenderPipelineState` are actually autoreleased instead of fully retained...despite their use of the standard `new...` Obj-C function naming paradigm. That autoreleased object would therefore be released in my demo...but not yours.

I'll experiment with wrapping the creation code in explicit autorelease pools, to avoid relying on the implicit threading autorelease pools.

**Comment by billhollings** [comment] 2019-10-07 23:26
@kuwerty PR #753 wraps shader and pipeline compiling in an autorelease block. Hopefully that fixes the leak under your app environment. Please retest and close this issue if successful.

**Comment by kuwerty** [comment] 2019-10-08 02:28
@billhollings Thanks for taking a look. Bad news: I tried the fix and that didn't seem to solve it :-(

Good news? I think I've got some theories as to what happens.

I was just trying to work out why you and I see different retain counts for the Metal pipeline objects and discovered that when 'GPU Frame Capture' is disabled in the Xcode run options that I get the same retain counts as you see (retain count of mtlPipelineState is 1 just before the release). Once GPU capture is re-enabled then I end up with retain counts of 2.

I left my simple app going for a minute or two with GPU capture enabled (but not capturing or anything, just left the option enabled) and using the memory graph debugger I can see 100,000s of live objects in the Metal module, all related to functions/pipelines/etc.

I ran my app again without GPU frame capture and even after 10 minutes there's hardly any objects live (nothing unexpected).

My guess is that there is a bug (or maybe Metal is intentionally tracking everything for the lifetime of the app) when GPU frame capture is enabled. Or maybe the only bug is that the fragment shaders show up as live in the resources view when they should be internally flagged as dead.

Seeing as this is something that only happens in development, it's not a killer for production code.  I'd be willing to close this bug as I don't think there's anything we can do about it.

**Comment by billhollings** [comment] 2019-10-08 19:06
>Bad news: I tried the fix and that didn't seem to solve it :-(

Ahhh...shoot!

Thanks for the further research. So it looks like Xcode is involved somehow in your environment.

Unfortunately I did not see the same effect when I was testing. Even with GPU capture enabled running...the only time I encountered bonus shader function instances was if I did not call `vkDestroyPipeline()`.

What environment are you running? I am running my sample app on iOS 13.1.2 using Xcode 11 on macOS 10.14.6. 

Unfortunately I can't use GPU capture on apps running on macOS itself using Xcode 11 until I upgrade to macOS 10.15.

>I left my simple app going

Is this simple app something you can ZIP up and post to the cloud somewhere (eg. Dropbox) and post a link here so I can experiment with it? If you can but don't want to post a public link...you can send the link to support@brenwill.com after you post it.

**Comment by kuwerty** [comment] 2019-10-09 05:44
Sorry, should've said that straight away.  I'm running a MacOS application on MacOS 10.14.6 using Xcode 10.3.

Let me post a link to the support email address later today.

**Comment by billhollings** [comment] 2019-10-15 15:22
> Let me post a link to the support email address later today.

After reviewing the demo app and Xcode...this appears to be an issue with Xcode 10 GPU capture under macOS 10.14. It is not occurring when GPU capture is turned off and does not occur at all in Xcode 11/macOS 10.15.

Closing this issue now. If the problem reappears, please reopen with additional info.

**Closed by billhollings** 2019-10-15 15:22 UTC
Labels: Bug, Requested more info
