### ISSUE TITLE
Xcode 10 issue with large number of vertices

### ISSUE THREAD

**Issue by titusdaking** [KhronosGroup/MoltenVK#445] opened 2019-01-08 22:27 UTC
I recently switched over to using Xcode 10 for my project from Xcode 9, and I have been experiencing some strange behavior when trying to render using large vertex buffers.  Additionally, memory usage seems to be much higher and performance much worse when running from Xcode 10.  I did clean build before running and the result was the same.  I thought that maybe I had made a mistake in my code, so I tried running vulkan-tutorial's code (directly copy-pasted), but it had the same issue.  Rendering works fine with small enough models, but this issue occurs with larger models.

Xcode 9 renders fine:
![xcode9](https://user-images.githubusercontent.com/46504684/50862595-056cfa80-136a-11e9-904a-0e12369f399c.png)

Xcode 10:
![xcode10](https://user-images.githubusercontent.com/46504684/50862612-1584da00-136a-11e9-85dc-441af2082f5f.png)

Any help would be greatly appreciated – I would love to move to Xcode 10 but this issue is preventing me from doing so.

**Comment by billhollings** [comment] 2019-01-09 17:48
Very strange. The version of Xcode used to build MoltenVK should not really matter.

Are you building and running the same version of MoltenVK in both cases?

Are you seeing any error messages being logged to the Xcode console?

**Comment by titusdaking** [comment] 2019-01-09 18:17
I am using the same version of MoltenVK in both cases, and I've tried both building myself and using prebuilt by the SDK.

I am not seeing any error messages or validation messages.

I have done some more testing, and I have found that my previous statement about vulkan-tutorial was wrong.  Vulkan-tutorial's example does work when running in Xcode 10.  The main difference between vulkan-tutorial's code and my code is that I am using VulkanMemoryAllocator – maybe VMA is not playing nice with Xcode 10?  I guess will have to do additional testing to see if this is the case...still very confused...

**Comment by KenThomases** [comment] 2019-01-09 20:38
You wrote "when running from Xcode 10". Do you literally mean when launching your app from Xcode 10 rather than when launching it from Xcode 9? Does a build of your app built by Xcode 10 exhibit problems when launched from the Finder?

If the problem is only when launching from Xcode 10, what diagnostic tools are enabled in the scheme? Does disabling any/all of them fix the problem?

**Comment by titusdaking** [comment] 2019-01-09 20:51
My mistake – I mean when building the app from Xcode 10.  Launching from finder does not resolve the issue.

**Comment by aerofly** [comment] 2019-01-10 08:36
We use MoltenVK on Mac OS and iOS without a dedicated memory allocator, e.g. we reserve memory for each texture and buffer we use, contrary to what you should use on Vulkan.

I don't think this is necessary with MoltenVK as Metal handles the proper memory handling here.

So using VulkanMemoryAllocator is likely causing the problems at least we saw issues ourself when initially using a dedicated allocator as well.

**Comment by titusdaking** [comment] 2019-01-10 20:06
Ah – I did not know that.  I guess I should have done my research on Metal.  So just clarifying, this means that the normal Vulkan restrictions on the number of VkDeviceMemory allocations do not apply when using MoltenVK because Metal internally handles allocations?

**Comment by billhollings** [comment] 2019-01-10 22:04
Metal has no concept equivalent to `VkDeviceMemory`(ie. memory as distinct objects independent of images and buffers)...so MoltenVK has to jump through some logistical hoops to map the memory underlying `VkDeviceMemory` objects to the `VkImage` and `VkBuffers` that use them.

This mapping is simplest when each `VkImage` and `VkBuffer` has a dedicated `VkDeviceMemory`.

And to answer your direct question...Metal has no specific limits on numbers of textures and buffers...so there is no specific limit on `VkDeviceMemory` instances either.

**Comment by billhollings** [comment] 2019-01-16 19:23
@titusdaking Do the responses on this thread fix your issue...or are you still encountering problems?

If all is good now...can you close this issue, please?

**Closed** 2019-01-17 20:56 UTC
Labels: question, requested more info
