### ISSUE TITLE
Vulkan compute shader that writes to same vec4 from different work items fails with MoltenVK 

### ISSUE THREAD

**Issue by elmar-k** [KhronosGroup/MoltenVK#942] opened 2020-06-29 05:13 UTC
Dear MoltenVK-Team,

here is the second thing I bumped into. It revolves around this question:

Is it allowed to write to the same vec4/float4 from different work items in a compute shader?

I searched the Vulkan and Metal specs, but couldn't find any mention of this topic. It works fine for me in Linux Vulkan, but fails with MoltenVK. The Metal code created by SPIRV-Cross looks fine, so this could very well be a bug in Metal. On the other hand, if this code is not allowed in Metal, but legal in Vulkan, then MoltenVK should raise an error (as it did when my Vulkan app tried to use triangle fans)

I stripped the problem down to this minimum examle:

I have a buffer filled with floats from 0 to 999:

for (j=0;j<1000;j++) ((float*)stagingbuff->mem.ptr)[j]=j;

And then use this compute shader, where each work item copies a single float in an array of vec4:

  /* CONVERT THE 2D WORKGROUP ID TO A SIMPLE LINEAR 1D INDEX (WORKGROUP SIZE ALONG X IS LIMITED) */
  #define gl_GlobalInvocationIndex2D (((gl_NumWorkGroups[0]*gl_WorkGroupID[1])+gl_WorkGroupID[0])*gl_WorkGroupSize[0]+gl_LocalInvocationID[0])
  
  layout(local_size_x=64,local_size_y=1,local_size_z=1) in;
  layout(set=VKP_DSDYN,binding=VKP_BNDVTX) buffer readonly srcballdata 
  { vec4 ball[]; } src;
  layout(set=VKP_DSDYN,binding=VKP_BNDBAL) buffer dstballdata          
  { vec4 ball[]; } dst; 
  
  void vk_main()
  { uint idx;
  
    idx=gl_GlobalInvocationIndex2D;
    dst.ball[idx>>2][idx&3]=src.ball[(idx>>2)][idx&3]; } }

After reading back the copied result in Linux, everything is as expected:

X=0.000000, Y=1.000000, Z=2.000000, W=3.000000
X=4.000000, Y=5.000000, Z=6.000000, W=7.000000
X=8.000000, Y=9.000000, Z=10.000000, W=11.000000
X=12.000000, Y=13.000000, Z=14.000000, W=15.000000
etc...

With MoltenVK, MacOS 10.14 and a Geforce GT750M, the copying does not work, note that
only the 4th element in each vector is copied correctly:

X=0.000000, Y=0.000000, Z=0.000000, W=3.000000
X=0.000000, Y=0.000000, Z=0.000000, W=7.000000
X=0.000000, Y=0.000000, Z=0.000000, W=11.000000
X=0.000000, Y=0.000000, Z=0.000000, W=15.000000
etc...

With MoltenVK, MacOS 10.15 and an Intel GPU, the copying also does not work, but this time the 1st element in each vector is copied correctly:

X=0.000000, Y=0.000000, Z=0.000000, W=0.000000
X=4.000000, Y=0.000000, Z=0.000000, W=0.000000
X=8.000000, Y=0.000000, Z=0.000000, W=0.000000
X=12.000000, Y=0.000000, Z=0.000000, W=0.000000
etc...

Looking at the metal shader code created from the Vulkan original with SPIRV-Cross, I cannot see a problem:

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct dstballdata
{
    float4 ball[1];
};

struct srcballdata
{
    float4 ball[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

kernel void main0(device dstballdata& dst [[buffer(0)]], const device srcballdata& src [[buffer(1)]], uint3 gl_NumWorkGroups [[threadgroups_per_grid]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    uint _29 = (((gl_NumWorkGroups.x * gl_WorkGroupID.y) + gl_WorkGroupID.x) * 64u) + gl_LocalInvocationID.x;
    uint _40 = _29 >> uint(2);
    uint _43 = _29 & 3u;
    dst.ball[_40][_43] = src.ball[_40][_43];
}

The problem can be "solved" by using a float array instead of a vec4 array:

  /* CONVERT THE 2D WORKGROUP ID TO A SIMPLE LINEAR 1D INDEX (WORKGROUP SIZE ALONG X IS LIMITED) */
  #define gl_GlobalInvocationIndex2D (((gl_NumWorkGroups[0]*gl_WorkGroupID[1])+gl_WorkGroupID[0])*gl_WorkGroupSize[0]+gl_LocalInvocationID[0])
  
  layout(local_size_x=64,local_size_y=1,local_size_z=1) in;
  layout(set=VKP_DSDYN,binding=VKP_BNDVTX) buffer readonly srcballdata  
  { float ball[]; } src;
  layout(set=VKP_DSDYN,binding=VKP_BNDBAL) buffer dstballdata           
  { float ball[]; } dst; 
  
  void vk_main()
  { uint idx;
  
    idx=vk_GlobalInvocationIndex2D;
    dst.ball[idx]=src.ball[idx]; } }

Which gives this Metal code that works correctly:

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct dstballdata
{
    float ball[1];
};

struct srcballdata
{
    float ball[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

kernel void main0(device dstballdata& dst [[buffer(0)]], const device srcballdata& src [[buffer(1)]], uint3 gl_NumWorkGroups [[threadgroups_per_grid]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    uint _29 = (((gl_NumWorkGroups.x * gl_WorkGroupID.y) + gl_WorkGroupID.x) * 64u) + gl_LocalInvocationID.x;
    dst.ball[_29] = src.ball[_29];
}

Using an array of floats is not an option in my case, since I really need vec4 (remember, this is just a stripped down example).

So my current workaround is to copy an entire vec4 in every 4th workitem, this also works correctly:

  /* CONVERT THE 2D WORKGROUP ID TO A SIMPLE LINEAR 1D INDEX (WORKGROUP SIZE ALONG X IS LIMITED) */
  #define gl_GlobalInvocationIndex2D (((gl_NumWorkGroups[0]*gl_WorkGroupID[1])+gl_WorkGroupID[0])*gl_WorkGroupSize[0]+gl_LocalInvocationID[0])
  
  layout(local_size_x=64,local_size_y=1,local_size_z=1) in;
  layout(set=VKP_DSDYN,binding=VKP_BNDVTX) buffer readonly srcballdata 
  { vec4 ball[]; } src;
  layout(set=VKP_DSDYN,binding=VKP_BNDBAL) buffer dstballdata          
  { vec4 ball[]; } dst; 
  
  void vk_main()
  { uint idx;
  
    idx=gl_GlobalInvocationIndex2D;
    if ((idx&3)==0) dst.ball[idx>>2]=src.ball[idx>>2]; } }

With correctly working Metal translation:

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct dstballdata
{
    float4 ball[1];
};

struct srcballdata
{
    float4 ball[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

kernel void main0(device dstballdata& dst [[buffer(0)]], const device srcballdata& src [[buffer(1)]], uint3 gl_NumWorkGroups [[threadgroups_per_grid]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    uint _29 = (((gl_NumWorkGroups.x * gl_WorkGroupID.y) + gl_WorkGroupID.x) * 64u) + gl_LocalInvocationID.x;
    if ((_29 & 3u) == 0u)
    {
        uint _47 = _29 >> uint(2);
        dst.ball[_47] = src.ball[_47];
    }
}

Best regards,
Elmar

**Comment by cdavis5e** [comment] 2020-06-29 06:18
Looking at the generated AIR code confirms that Metal is storing the entire vector at once; i.e. instead of doing this:
```c++
v.x = a;
```
it's doing this:
```c++
v = float4(a, v.yzw);
```
This is an unfortunate consequence of the way MSL code is compiled down. There isn't much we can do. If you think this is wrong, I suggest filing a feedback with Apple.

**Comment by billhollings** [comment] 2020-06-29 15:23
@cdavis5e 

Thanks for going to the trouble to inspect the AIR code!

>v = float4(a, v.yzw);

I'm curious...(me not having seen the compiled code around this)...since the copying is done in order, shouldn't this work anyway? Shouldn't the next copy (say maybe the equivalent of `v = float4(v.x, b, v.zw)`) pick up the value of `a` from the `v.x` part? Or is it optimizing in a way that only reads the entire `v` once?

**Comment by billhollings** [comment] 2020-06-29 15:26
@elmar-k 

Thanks for posting your findings.

>So my current workaround is to copy an entire vec4 in every 4th workitem, this also works correctly

Another option to explore might be to assign the value to a temp `float` var in between the read and write assignments...which may or may not be more expensive than the `if()` branch (and frankly which may or may not work anyway depending on equivalent optimizations by the Metal compiler)?

Given @cdavis5e 's research, if either that, or your, workaround is sufficient, can we close this issue?

**Comment by cdavis5e** [comment] 2020-06-29 18:33
> I'm curious...(me not having seen the compiled code around this)...since the copying is done in order, shouldn't this work anyway? Shouldn't the next copy (say maybe the equivalent of `v = float4(v.x, b, v.zw)`) pick up the value of `a` from the `v.x` part? Or is it optimizing in a way that only reads the entire `v` once?

No. The problem is that these `float4` writes are happening concurrently. In fact, given SIMD-group locality, they're probably happening simultaneously. There's no ordering between them. That's why sometimes, only the first element is written, and other times only the last element is written.

**Comment by billhollings** [comment] 2020-06-29 18:49
>writes are happening concurrently

D'oh! Of course they are. 🤦🏻‍♂️

**Comment by elmar-k** [comment] 2020-06-30 17:03
Hi Bill,

many thanks for the quick reply.

Since this is a silent shader failure and among the most difficult things to debug, I wanted to report it so that you can decide what to do next so that other users have a working MoltenVK experience.

You could for example suggest Apple to fix it on their side (since MoltenVK is Apple's life-saver that prevents us and many other companies from dropping the platform, they will certainly have an open ear whenever you get in touch).

If Apple says it's a feature, not a bug, then SPIRV-Cross or MoltenVK could somewhere detect such partial writes from different work items and raise an error that this GLSL shader cannot be translated to Metal and needs to be changed.

I'm happy with my workaround and don't need any additional help...

Best regards,
Elmar

**Comment by HansKristian-Work** [comment] 2020-06-30 17:41
That does indeed look like a Metal bug. What happens if you use packed_float4 instead? Perhaps that blocks the compiler from assuming whole vectors.

**Comment by cdavis5e** [comment] 2020-06-30 18:20
> What happens if you use packed_float4 instead?

That now only stores the element that was written. In the generated AIR code, an array of float `[4 x float]` is used instead of a vector of float `<4 x float>`. Apparently, LLVM, which AIR is based on, can only load and store whole vectors.

> Also, what happens if you access the float by array index ala `float4 v; v[0] = 1.0;`?

That's what OP's original code does.

**Comment by HansKristian-Work** [comment] 2020-06-30 18:25
I'm pretty sure LLVM IR supports getelementptr into a vector, so that's surprising ...

**Comment by HansKristian-Work** [comment] 2020-06-30 18:32
https://llvm.org/docs/GetElementPtr.html#can-gep-index-into-vector-elements hm ...

**Comment by HansKristian-Work** [comment] 2020-06-30 18:36
I wonder if we could workaround this somehow by looking for any scalar write to a vector type in either device or threadgroup address spaces (please no ...), and force packed types for that member.

**Comment by cdavis5e** [comment] 2020-06-30 18:37
> I wonder if we could workaround this somehow by looking for any scalar write to a vector type in either device or threadgroup address spaces (please no ...), and force packed types for that member.

I don't know... That could adversely affect struct layout.

**Comment by HansKristian-Work** [comment] 2020-06-30 18:40
It "should" just work, but this is a somewhat scary change to make for sure, and I hate it ...

**Comment by HansKristian-Work** [comment] 2020-06-30 19:21
Apparently, this is working as intended, guess I'll have no choice but to workaround this ... :(

**Comment by mbarriault** [comment] 2020-06-30 19:28
Been watching this this silently, just want to add the question: does this work on other platforms because it's genuinely defined behaviour, or because it happens to work but it's technically undefined? For example, intuitively I wouldn't expect to be able to write to the red and green components of the same pixel of an image in different threads.

**Comment by HansKristian-Work** [comment] 2020-06-30 19:28
It is well-defined on all other APIs.

**Comment by billhollings** [comment] 2020-06-30 20:58
>an array of float [4 x float] is used instead of a vector of float <4 x float>

Yeah...makes sense. Packed types don't support `.xyzw`, and require access via `[.]`.

>force packed types for that member

When converting, treat `float3` as `packed_float4` to preserve structure sizing? Alignment will still be problematic. There is padding code in `CompilerMSL` to help with that though.

**Comment by billhollings** [comment] 2020-07-06 17:39
@elmar-k 

This is fixed in PR #946, based on [this fix in SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/pull/1416). 

Please retest and close this issue if it fixes your issue.

**Comment by billhollings** [comment] 2020-07-21 20:23
Closing now.

**Closed by billhollings** 2020-07-21 20:23 UTC
Labels: Answered, Bug, Fixed - please test & close, Question
