### ISSUE TITLE
vkDestroyDebugUtilsMessengerEXT requires vkGetInstanceProcAddr

### ISSUE THREAD

**Issue by c0nd3v** [KhronosGroup/MoltenVK#355] opened 2018-11-25 22:31 UTC
title

**Comment by billhollings** [comment] 2018-11-27 19:15
@c0nd3v 

Can you provide more info about what you are trying to do...and what this error report is about?

Are you trying to call `PFN_vkDestroyDebugUtilsMessengerEXT`?

MoltenVK does not yet support the `VK_EXT_debug_utils` extension that provides that function...and so `vkGetInstanceProcAddr` will return a null pointer in that case.

**Comment by c0nd3v** [comment] 2018-11-27 21:36
MoltenVK does support VK_EXT_debug_utils

???

**Comment by c0nd3v** [comment] 2018-11-27 21:37
When compiling vkDestroyDebugUtilsMessengerEXT fails to link. so I must use vkGetInstanceProcAddr at runtime.

**Comment by karl-lunarg** [comment] 2018-11-27 23:18
@c0nd3v must be using the loader and validation layers.

`VK_EXT_debug_utils` is largely implemented in the loader and validation layers and doesn't necessarily need to be implemented by a driver to be useful, since the extension was designed primarily as a vehicle for delivering validation status to the application from the validation layers.

I think that a driver _could_ implement it, but I think MoltenVK does its own thing by sending "Metal validation" errors to stderr if the MoltenVK library is compiled for debugging.

And yes, you need to call `vkInstanceGetProcAddr` for all instance extension functions.  The Vulkan loader exports only the core functions and the WSI extensions.  See the [examples](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_EXT_debug_utils) in the Vulkan specification or the source code for the cube demo to see how the function pointers are obtained for using this extension.

I don't think that there's any further action here.  Working as designed.

**Comment by billhollings** [comment] 2018-11-28 19:38
@karl-lunarg 

Thanks for the explanation...and for clarifying the support for `VK_EXT_debug_utils` in the loader and validation layers.

@c0nd3v 

As @karl-lunarg explains...since MoltenVK itself does not support `VK_EXT_debug_utils`, you cannot link directly to `vkDestroyDebugUtilsMessengerEXT`...and using `PFN_vkDestroyDebugUtilsMessengerEXT` via `vkGetInstanceProcAddr` in the loader and validation layers is required.

I'm going to close this particular issue. If there is a priority for MoltenVK as a driver to support `VK_EXT_debug_utils` sooner rather than later...please open a new issue requesting that.

**Closed by billhollings** 2018-11-28 19:38 UTC
Labels: requested more info
