### ISSUE TITLE
vkQueueSubmit leaks memory over time

### ISSUE THREAD

**Issue by Dolphiniac** [KhronosGroup/MoltenVK#634] opened 2019-06-05 21:44 UTC
Hello, all!  I'm working in a project using MoltenVK to target our Mac and iOS platforms, and I've noticed a steadily rising memory footprint in the XCode window (~50KiB/s).  This leak is completely halted if I disable the frame's vkQueueSubmit call.  

Noticing issue #103 when writing this issue, I tried disabling the fence in the call and calling vkQueueWaitIdle directly after submitting with no change.  MVKConfiguration::synchronousQueueSubmits is set to VK_TRUE.

Running MoltenVK from SDK version 1.1.106.0.

**Comment by billhollings** [comment] 2019-06-06 02:21
@Dolphiniac 

I'm not able to reproduce any MoltenVK leaks using apps I have access to.

Are you able to post a link to an app that demonstrates the issue?

Or can you run Xcode Instruments and identify the source of the leaks?

**Comment by Dolphiniac** [comment] 2019-06-14 20:50
Update:  I made a dead simple Cocoa app with straight Vk code in `AppDelegate::applicationDidFinishLaunching`.  Beyond creation of the device and retrieval of the queue, I just called `vkQueueWaitIdle` in a loop, and the memory footprint was increasing as I saw previously.

After stepping through what MVK was doing, I noticed that the footprint increases atomically on the stub MTLCommandBuffer `commit` call that facilitates the wait.  Since this code was protected by an autoreleasepool, I didn't see anything wrong with it, so I did a little more research and found that someone had a leak with GPU frame capture enabled.  Disabling this option stopped the leak.

**Comment by billhollings** [comment] 2019-06-16 19:35
@Dolphiniac  

Thanks for the feedback. Good to know that it only appears under certain debug conditions.

Are you able to ZIP up that little test app and post it to the cloud somewhere so we can download it and try to resolve the origin of the leak anyway?

**Comment by billhollings** [comment] 2019-09-19 19:07
Closing. Reopen if this issue is identifiable.

**Comment by Valakor** [comment] 2020-10-09 19:09
I'd like to re-open this for discussion. It seems that I'm leaking 64 bytes every time I call `vkQueuePresentKHR`. I'm using the pre-built binaries from the 1.2.154.0 SDK that was recently released, default MoltenVK environment settings, and macOS 10.15.7 (though I'm pretty sure I've noticed this behavior on previous version of MoltenVK and macOS). The callstack in Instruments for all of the leaked allocations looks like this:
```
   0 libsystem_malloc.dylib malloc_zone_calloc
   1 libsystem_malloc.dylib calloc
   2 libdispatch.dylib _dispatch_continuation_alloc_from_heap
   3 libdispatch.dylib dispatch_after
   4 QuartzCore -[CAMetalDrawable addPresentScheduledHandler:]
   5 Metal -[_MTLCommandBuffer presentDrawable:]
   6 AMDMTLBronzeDriver -[BronzeMtlCmdBuffer presentDrawable:]
   7 libMoltenVK.dylib MVKPresentableSwapchainImage::presentCAMetalDrawable(id<MTLCommandBuffer>, bool, unsigned int, unsigned long long)
   8 libMoltenVK.dylib MVKQueuePresentSurfaceSubmission::execute()
   9 libMoltenVK.dylib MVKQueue::submit(VkPresentInfoKHR const*)
  10 libMoltenVK.dylib vkQueuePresentKHR
```
I'm fairly certain that I'm profiling with Metal frame capture and validation both disabled. Briefly browsing through `MVKQueue.mm` I don't see an autorelease pool or similar wrapping this particular present code path, though I don't claim to fully understand obj-c referencing counting and all that...

**Comment by jkolb** [comment] 2022-10-23 18:57
I am seeing the same issue, I think this manages to get rid of it:

```
drawable->retain();
commandBuffer->addScheduledHandler(^(MTL::CommandBuffer *cb){
    drawable->present();
    drawable->release();
});
//commandBuffer->presentDrawable(drawable);
commandBuffer->commit();
```

I tried the above on a whim after reading the [Metal Best Practices Guide](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/Drawables.html)

> [presentDrawable:](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443029-present) is a convenience method that calls the given drawable's [present](https://developer.apple.com/documentation/metal/mtldrawable/1470284-present) method via the command buffer's [addScheduledHandler:](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1442991-addscheduledhandler) callback.

**Comment by billhollings** [comment] 2022-10-31 20:29
> I am seeing the same issue, I think this manages to get rid of it:

Hmmm...you're using an older version of MoltenVK, which hasn't used `presentDrawable:` since the[ SDK 1.2.162 release (MoltenVK 1.1.1)](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.1) at the end of 2020, and which includes a similar move to using `MTLCommandBuffer addScheduledHandler:`. So this leak is either already fixed, or has a different form.

Are you able to update to a more recent MoltenVK version (ideally to [ SDK 1.3.231 release (MoltenVK 1.2.0)](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.0), which also includes support for Vulkan 1.2)?

**Closed by billhollings** 2022-10-31 20:29 UTC
Labels: Bug
