### ISSUE TITLE
[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: vkCreateDevice(): Requested feature is not available on this device.

### ISSUE THREAD

**Issue by M1Minecraft** [KhronosGroup/MoltenVK#1625] opened 2022-06-18 00:05 UTC
This error shows up for Mac when running a game through Crossover. I'm not much knowledgeable in this area but I've read somewhere that this is not supported on Mac, I think it's related to "wide lines". Could metal 3 potentially support wide lines, or is it still not possible?

**Comment by cdavis5e** [comment] 2022-06-18 04:26
There is no *public* API in Metal for wide lines.

**Comment by billhollings** [comment] 2022-07-27 22:05
Closing as duplicate of #1657.

**Closed by billhollings** 2022-07-27 22:05 UTC
Labels: Duplicate
