### ISSUE TITLE
1.2.8 release build failure

### ISSUE THREAD

**Issue by chenrui333** [KhronosGroup/MoltenVK#2204] opened 2024-04-09 03:01 UTC
👋 trying to build the latest release, but run into some build issue only on ventura OS. The error log is as below:

<details>
<summary>error build log</summary>

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:6247366C-7B06-5EF1-A00C-F983162807B1 }
{ platform:macOS, name:Any Mac }
Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (6 targets)
    Target 'MoltenVK-macOS' in project 'MoltenVKPackaging'
        ➜ Explicit dependency on target 'MoltenVK-macOS-dylib' in project 'MoltenVK'
        ➜ Explicit dependency on target 'MoltenVK-macOS-dynamic' in project 'MoltenVK'
    Target 'MoltenVK-macOS-dynamic' in project 'MoltenVK'
        ➜ Explicit dependency on target 'MoltenVK-macOS-static' in project 'MoltenVK'
    Target 'MoltenVK-macOS-dylib' in project 'MoltenVK'
        ➜ Explicit dependency on target 'MoltenVK-macOS-static' in project 'MoltenVK'
    Target 'MoltenVK-macOS-static' in project 'MoltenVK'
        ➜ Explicit dependency on target 'MoltenVKShaderConverter' in project 'MoltenVKShaderConverter'
    Target 'MoltenVKShaderConverter' in project 'MoltenVKShaderConverter'
        ➜ Explicit dependency on target 'MoltenVKShaderConverter-macOS' in project 'MoltenVKShaderConverter'
    Target 'MoltenVKShaderConverter-macOS' in project 'MoltenVKShaderConverter' (no dependencies)

GatherProvisioningInputs

CreateBuildDescription
Build description signature: 3918dd953524707f15a31423e366fcb9
Build description path: /tmp/molten-vk-20240402-5068-hh65m1/MoltenVK-1.2.8/build/Build/Intermediates.noindex/XCBuildData/3918dd953524707f15a31423e366fcb9.xcbuilddata

error: There is no XCFramework found at '/tmp/molten-vk-20240402-5068-hh65m1/MoltenVK-1.2.8/External/build/Latest/SPIRVTools.xcframework'. (in target 'MoltenVKShaderConverter-macOS' from project 'MoltenVKShaderConverter')
error: There is no XCFramework found at '/tmp/molten-vk-20240402-5068-hh65m1/MoltenVK-1.2.8/External/build/Latest/SPIRVCross.xcframework'. (in target 'MoltenVKShaderConverter-macOS' from project 'MoltenVKShaderConverter')
error: There is no XCFramework found at '/tmp/molten-vk-20240402-5068-hh65m1/MoltenVK-1.2.8/External/build/Latest/glslang.xcframework'. (in target 'MoltenVKShaderConverter-macOS' from project 'MoltenVKShaderConverter')
note: Run script build phase 'Package MoltenVK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'MoltenVK-macOS' from project 'MoltenVKPackaging')
** BUILD FAILED **
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/8523906852/job/23347741567
relates to Homebrew/homebrew-core#166005

**Comment by cdavis5e** [comment] 2024-04-09 05:59
Did you run the `fetchDependencies` script?

**Comment by cdavis5e** [comment] 2024-04-09 06:16
Hmm... looking at your build failure, it looks like Homebrew manually runs most of the steps that `fetchDependencies` would perform. But before it could write out the `*.xcframework` bundles, it [failed to connect to some database](https://github.com/Homebrew/homebrew-core/actions/runs/8523906852/job/23347741567#step:3:4604). I wonder if you weren't just hit with some transient failure. Does it work when you run it again, or is this failure reliably reproducible?

**Comment by chenrui333** [comment] 2024-04-13 18:24
yeah, initially I was thinking it would be transient failure, but it is pretty consistent with bunch of retries.

**Comment by billhollings** [comment] 2024-04-15 19:37
Since this appears to be a Homebrew internal issue, I'm not sure what we can do here. I note that the Homebrew issue you referenced above is also closed now.

I'm going to close this. If there is something actionable within MoltenVK that someone working on the Homebrew tap can identify, please open another issue.

**Closed by billhollings** 2024-04-15 19:37 UTC
Labels: Not a bug
