### ISSUE TITLE
Vulkan SDK release feature cut-off Friday June 25

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1386] opened 2021-06-17 19:36 UTC
LunarG is planning the next Vulkan SDK release in the week of Monday June 28.

MoltenVK PRs approved by Friday June 25 will be included, and a MoltenVK SDK release will be made Monday June 28.

@cdavis5e @HansKristian-Work @richard-lunarg

**Comment by MennoVink** [comment] 2021-06-21 15:04
Could you provide some input on https://github.com/KhronosGroup/MoltenVK/issues/1178? I've asked some feedback there but the issue is still on "Requested more info" so perhaps we're waiting for each other?

**Comment by billhollings** [comment] 2021-06-21 15:33
@MennoVink Thanks for the prod. I'll try to look at #1178 this week before the SDK build.

**Comment by KarenGhavam-lunarG** [comment] 2021-06-24 15:11
@billhollings We are ahead of schedule and have the branches/commits for the SDK. [This config.json file](https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/blob/master/SDK_creation/common/config.json) shows all the branches/commits and you can get the commits from it that you need for glslang, Vulkan-Headers, and Vulkan-Tools. If an entry has both branch and tag, the tag is not yet committed. So use the ToT for the branch.

We will go ahead and begin Windows and Linux SDK builds. Richard will start macOS SDK builds on Monday, so if you could have the MoltenVK build to him by Monday AM that would be helpful.

**Comment by billhollings** [comment] 2021-06-24 19:52
@KarenGhavam-lunarG Thanks for the SDK commits. Monday AM should be fine.

**Comment by billhollings** [comment] 2021-06-28 15:25
MoltenVK [v1.1.4](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.4) is now released for SDK 1.2.182.

**Closed** 2021-07-09 13:05 UTC
Labels: SDK Coordination
